### ISSUE TITLE
Esp32-c6 supported from Platformio

### ISSUE THREAD

**Issue by simogaspa84** [espressif/arduino-esp32#7754] opened 2023-01-25 14:47 UTC
### Related area

MCU support for Platformio and arduino framework

### Hardware specification

Esp32-c6

### Is your feature request related to a problem?

I would like to request the compatibility of platformio and arduino framework wih the following chip esp32c6

https://espressif-docs.readthedocs-hosted.com/projects/espressif-esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide.html

### Describe the solution you'd like

Same solution of today with normal versions of esp32

### Additional context

https://espressif-docs.readthedocs-hosted.com/projects/espressif-esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitc-1/user_guide.html

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by VojtechBartoska** [comment] 2023-01-25 14:58
Hello, closing this as duplicate of https://github.com/espressif/arduino-esp32/issues/7713.

There is more details about support of C6, is really to early to say more right now.

Thanks for understanding.

**Closed by VojtechBartoska** 2023-01-25 14:58 UTC
Labels: Type: Feature request
