### ISSUE TITLE
ESPNOW Setup Question

### ISSUE THREAD

**Issue by m0nki** [espressif/arduino-esp32#1031] opened 2018-01-25 10:45 UTC
I have 3 x ESP32s and want to send sensor data from two of them to one connected to PC via serial (so I can suck data into PC for manipulation). 
Most of the code examples I have seen are for multislave environment but I think I am looking for a multimaster setup? Just trying to get my head around how ESPNOW works but feel I might be completely missing something.  Can anyone point me to some code with two ESP's sending data to another one via ESPNOW? Thanks any helpful advice welcome.

**Comment by beegee-tokyo** [comment] 2018-01-25 12:11
[ESPNow examples](https://github.com/espressif/arduino-esp32/tree/4c36e033812a4142ba417565926ff8f919a32646/libraries/ESP32/examples/ESPNow)

**Comment by dpharris** [comment] 2018-01-25 18:07
Thanks.
Is ESPNow incompatible with regular Wifi use? -- ie can an ESP32 be used as
a bridge between several ESPNow 'slaves' and the wider net?

David

**Comment by beegee-tokyo** [comment] 2018-01-26 00:25
I got ESPNow and connection to AP working, but AP must be on WiFi channel 0. [Example](http://wiki.giesecke.tk/doku.php?id=tips_tricks:espnow_not_working)

**Comment by dpharris** [comment] 2018-01-26 02:04
@beegee-yokyo ... thanks for that, and good news.

**Comment by everslick** [comment] 2018-04-19 11:37
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 11:37 UTC
