### ISSUE TITLE
error while compiling dmp6 example of I2cdev libary for mpu6050

### ISSUE THREAD

**Issue by anhtu0310** [espressif/arduino-esp32#715] opened 2017-10-10 05:34 UTC
Hi , i have been trying to compile the MPU6050_DMP6  example of Jeff Rowberg's i2cdevlib anh i got this 

`
typedef uint32_t prog_uint32_t;
In file included from C:\Users\Anh e: previous declaration as 'typedef long unsigned int prog_uint32_t'
 typedef unsigned long prog_uint32_t `
so can you help me with this issue , thanks

**Comment by stickbreaker** [comment] 2017-10-10 06:56
Comment out one of them. 
You will have to identify which one is unnecessary.

chuck.

**Comment by agcaahmet** [comment] 2017-10-10 07:13
You may also refer to #53

**Comment by everslick** [comment] 2018-04-19 07:38
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 07:38 UTC
