### ISSUE TITLE
How to install it in linux?

### ISSUE THREAD

**Issue by suelio1** [espressif/arduino-esp32#818] opened 2017-11-08 03:35 UTC
Please fill the info fields, it helps to get you faster support ;)

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
Describe your problem here

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by beegee-tokyo** [comment] 2017-11-08 05:31
Maybe I misunderstand your question but did you do a [search](https://duckduckgo.com/?q=platformIO+install+linux&atb=v42-7ds&ia=web)
and then first result leads to [Docs » PlatformIO Core » Installation](http://docs.platformio.org/en/latest/installation.html)

**Comment by suelio1** [comment] 2017-11-08 05:53
@beegee-tokyo thanks. I already installed

**Comment by everslick** [comment] 2018-04-19 08:40
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 08:40 UTC
