### ISSUE TITLE
Simple time example doesn't work

### ISSUE THREAD

**Issue by Plumal73** [espressif/arduino-esp32#7401] opened 2022-10-26 14:43 UTC
### Board

ESP32 C3 DevKitM1

### Device Description

I use :
- Espressif ESP32-C3-DevKitM-1
- Arduino IDE 1.8.15
- ESP32 boards on Arduino IDE V2.0.5

### Hardware Configuration

Don't use any GPIO output

### Version

v2.0.5

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

Hello,

When I try to upload this basic example (I didn't change anything in the code) I've an issue on my serial monitor.

Here is what I have issue which is visible on Debug Part

I tried to use ESP Exception decoder but it didn't worked when I tyr to paste that in.
I change my usb one time but changed nothing.

Do u have an idea ?

P.S : Sorry for my english

### Sketch

```cpp
#include <WiFi.h>
#include "time.h"
#include "sntp.h"

const char* ssid       = "________";
const char* password   = "________";

const char* ntpServer1 = "pool.ntp.org";
const char* ntpServer2 = "time.nist.gov";
const long  gmtOffset_sec = 3600;
const int   daylightOffset_sec = 3600;

const char* time_zone = "CET-1CEST,M3.5.0,M10.5.0/3";  // TimeZone rule for Europe/Rome including daylight adjustment rules (optional)

void printLocalTime()
{
  struct tm timeinfo;
  if(!getLocalTime(&timeinfo)){
    Serial.println("No time available (yet)");
    return;
  }
  Serial.println(&timeinfo, "%A, %B %d %Y %H:%M:%S");
}

// Callback function (get's called when time adjusts via NTP)
void timeavailable(struct timeval *t)
{
  Serial.println("Got time adjustment from NTP!");
  printLocalTime();
}

void setup()
{
  Serial.begin(115200);

  // set notification call-back function
  sntp_set_time_sync_notification_cb( timeavailable );

  /**
   * NTP server address could be aquired via DHCP,
   *
   * NOTE: This call should be made BEFORE esp32 aquires IP address via DHCP,
   * otherwise SNTP option 42 would be rejected by default.
   * NOTE: configTime() function call if made AFTER DHCP-client run
   * will OVERRIDE aquired NTP server address
   */
  sntp_servermode_dhcp(1);    // (optional)

  /**
   * This will set configured ntp servers and constant TimeZone/daylightOffset
   * should be OK if your time zone does not need to adjust daylightOffset twice a year,
   * in such a case time adjustment won't be handled automagicaly.
   */
  configTime(gmtOffset_sec, daylightOffset_sec, ntpServer1, ntpServer2);

  /**
   * A more convenient approach to handle TimeZones with daylightOffset 
   * would be to specify a environmnet variable with TimeZone definition including daylight adjustmnet rules.
   * A list of rules for your zone could be obtained from https://github.com/esp8266/Arduino/blob/master/cores/esp8266/TZ.h
   */
  //configTzTime(time_zone, ntpServer1, ntpServer2);

  //connect to WiFi
  Serial.printf("Connecting to %s ", ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
  }
  Serial.println(" CONNECTED");

}

void loop()
{
  delay(5000);
  printLocalTime();     // it will take some time to sync time :)
}
```

### Debug Message

```plain
Rebooting...
ESP-ROM:esp32c3-20200918
Build:Sep 18 2020
rst:0x3 (RTC_SW_SYS_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40381976
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x38c
load:0x403ce000,len:0x6ac
load:0x403d0000,len:0x24e4
entry 0x403ce000
Connecting to YOUR_SSID Guru Meditation Error: Core  0 panic'ed (Illegal instruction). Exception was unhandled.

Core  0 register dump:
MEPC    : 0x40001be4  RA      : 0x420689ae  SP      : 0x3fca3130  GP      : 0x3fc8e400  
TP      : 0x3fc90e38  T0      : 0x40057fa6  T1      : 0x4038362a  T2      : 0xffffffff  
S0/FP   : 0x3fc95198  S1      : 0x40383b02  A0      : 0x3fc8f33c  A1      : 0x40383a04  
A2      : 0x4038528a  A3      : 0x40383746  A4      : 0x4038377e  A5      : 0x3fcdf4f8  
A6      : 0x40383814  A7      : 0x403837e8  S2      : 0x3c09dfa4  S3      : 0x00000002  
S4      : 0x3fc95000  S5      : 0x3fce0000  S6      : 0x3fce0000  S7      : 0x3fce0000  
S8      : 0x3ff1b000  S9      : 0x3fce0000  S10     : 0x3fcdf8d4  S11     : 0x00000000  
T3      : 0x40383f60  T4      : 0x40383cf6  T5      : 0x3fc8f000  T6      : 0x42011a9a  
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000002  MTVAL   : 0x00000000  
MHARTID : 0x00000000  

Stack memory:
3fca3130: 0x00000001 0x3fca5790 0x3fca5790 0x42068d86 0x52520000 0x484c4c50 0x4648484c 0x4446464a
3fca3150: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3170: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3190: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca31b0: 0x00000000 0x00000000 0x00000000 0x00000000 0x3fc95000 0x3fce0000 0x3fce0000 0x00001102
3fca31d0: 0x00000003 0x00000002 0x3fca5790 0x42032b90 0x00000000 0x00000000 0x43a1df7c 0x40383c10
3fca31f0: 0x3fce0000 0x3fce0000 0x3fce0000 0x3fc92980 0x3fc95000 0x3fc95620 0x3fc95628 0x42032c04
3fca3210: 0x00000000 0x3fc93000 0x3fce0000 0x4204bb36 0x3fca32e4 0x00000001 0x3fca10bc 0x00000001
3fca3230: 0x3fc92980 0x00000001 0x00000000 0x4204c472 0x3fce0000 0x3fce0000 0x3fc94d50 0x3ff1b594
3fca3250: 0x3fc92980 0xffffffff 0x3fc99704 0x4204aa18 0x00000000 0x3fcdf918 0x3fce0000 0x4003fe8a
3fca3270: 0x00000000 0x00000000 0x00000006 0x3fc99704 0x00000000 0x00000000 0x00000000 0x00000000
3fca3290: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x4038994c
3fca32b0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fca32d0: 0xa5a5a5a5 0xbaad5678 0x00000160 0xabba1234 0x00000154 0x3fca31a0 0x7bab36b4 0x3fc92694
3fca32f0: 0x3fc92694 0x3fca32e4 0x3fc9268c 0x00000002 0x3fca11f8 0x3fca11f8 0x3fca32e4 0x00000000
3fca3310: 0x00000017 0x3fca18d4 0x69666977 0x1697fe00 0xf4dd7544 0x000772d2 0x00000000 0x3fca32d0
3fca3330: 0x00000017 0x00000001 0x00000000 0x00000000 0x00000000 0x3fc967f4 0x3fc9685c 0x3fc968c4
3fca3350: 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000 0x4206f460 0x00000000
3fca3370: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3390: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca33b0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca33d0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca33f0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3410: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3430: 0x00000000 0xba000000 0xbaad5678 0x000008b4 0xabba1234 0x000008a8 0xdeadbeef 0x00000000
3fca3450: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3470: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3490: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca34b0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca34d0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca34f0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca3510: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000



ELF file SHA256: 0000000000000000


And repeat repeat ... repeat... repeat again..
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Plumal73** [comment] 2022-11-02 15:40
Hello, 

I tried different USB cable and USB port, doesn't change. I bought one more card and I'll test with it tomorrow. 

To answer your question, yes the crash happens after turning on the Wifi (I tried to write"Hello world" before turning on the wifi, and I saw "Hello world" in my Serial Terminal).

Do u have another idea ?

Thanks

**Comment by VojtechBartoska** [comment] 2023-01-18 10:01
@PilnyTomas can you please retest the example if it works smoothly? Thanks

**Comment by PilnyTomas** [comment] 2023-01-18 14:44
Hi, I was not able to reproduce this error:
ESP32-C3
Linux

**Comment by VojtechBartoska** [comment] 2023-01-18 15:11
I'm closing this as won't fix, if needed, you can reopen it. Thanks.

**Closed by VojtechBartoska** 2023-01-18 15:11 UTC
Labels: Resolution: Awaiting response, Status: Community help needed, Type: Example
