### ISSUE TITLE
AWS IoT Core not connecting when using with classic bluetooth. 

### ISSUE THREAD

**Issue by ranjitlawand** [espressif/arduino-esp32#8436] opened 2023-07-20 13:58 UTC
### Board

ESP32 Dev Module (4MB)

### Device Description

ESP32 Dev Module

### Hardware Configuration

#define RXD2 16
#define TXD2 17
#define RXD3 15
#define TXD3 13
#define RECIVE_ENABLE1 5
#define RECIVE_ENABLE2 4
#define WIFII_STATE 19
#define GREEN 32
#define RED 33
#define BLUE 25
#define WifiReset 18

### Version

v2.0.7

### IDE Name

PlatformIO

### Operating System

Windoes 11

### Flash frequency

240

### PSRAM enabled

no

### Upload speed

921600

### Description

I'm trying to connect to AWS IoT Core using ESP32. I also want to use Classic Bluetooth to communicate with the mobile phone. I have attached the sket for reference. 

The ini file is as follows
```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	knolleary/PubSubClient@^2.8
	powerbroker2/SerialTransfer@^3.1.3
	bblanchon/ArduinoJson@^6.21.1
	ldab/esp32_ftpclient@^0.1.4
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.partitions = no_ota.csv
upload_speed = 921600
; build_flags = -DCORE_DEBUG_LEVEL=5
monitor_filters = esp32_exception_decoder
```

Case 1:
When the wifi is connected and the AWS IoT connection is established before turning on the Classic Bluetooth core the ESP32 works till the Bluetooth connection is established post which ESP32 crashes. 
```
.
.
Connected to WiFi
Connecting to MQTT broker...
Connected to MQTT broker
Bluetooth initialized
The device started, now you can pair it with bluetooth
BT Callback Event: 0
BT Callback Event: 28

assert failed: vQueueDelete queue.c:2131 (pxQueue)


Backtrace: 0x40083695:0x3fff51d0 0x400930d1:0x3fff51f0 0x40098b3d:0x3fff5210 0x400944ee:0x3fff5340 0x40122d35:0x3fff5360 0x40121c74:0x3fff5380 0x40121cc2:0x3fff53a0 0x4010b497:0x3fff53c0 0x4010ce2a:0x3fff53f0 0x4010d094:0x3fff5410 0x4013f97d:0x3fff5450 0x4010e152:0x3fff54b0 0x4012288f:0x3fff54d0




ELF file SHA256: b384bb747de10cbb

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
```

Case 2:
When the Bluetooth is initialized before connecting to WiFi, the ESP32 is unable to connect to the AWS IoT Core with the following message.
```
Bluetooth initialized
The device started, now you can pair it with bluetooth
.
BT Callback Event: 0
BT Callback Event: 28
.
.
.
Connected to WiFi
Connecting to MQTT broker...
[  4364][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():273]: (-15104) PK - The pubkey tag or value is invalid (only RSA and EC are supported)
[  4367][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -15104
Failed, rc= Retrying in 5 seconds...
Connecting to MQTT broker...
[  6509][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():273]: (-16256) PK - Memory allocation failed
[  6510][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -16256
Failed, rc= Retrying in 5 seconds...
Connecting to MQTT broker...
[  8768][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():273]: (-16256) PK - Memory allocation failed
[  8769][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -16256
Failed, rc= Retrying in 5 seconds...
```

### Sketch

```cpp
#include <Arduino.h>

#include <BluetoothSerial.h>
#include <WiFiClientSecure.h>
#include <PubSubClient.h>
#include "secrets.h"
#include "Wire.h"
#include <WiFi.h>
#include <ESP32_FTPClient.h>
#include "SPIFFS.h"
#include <ArduinoJson.h>
#include "SerialTransfer.h"
#include "stdbool.h"
#include <HTTPClient.h>

#define RXD2 16
#define TXD2 17
#define RXD3 15
#define TXD3 13
#define RECIVE_ENABLE1 5
#define RECIVE_ENABLE2 4
#define WIFII_STATE 19

#define GREEN 32
#define RED 33
#define BLUE 25

#define WifiReset 18

String receivedBluetooth = "";

bool btCmdRxCbFlag = false;

String deviceId = "1091279764823";

static unsigned long long currentMillis = 0;
static unsigned long long previousMillis = 0;
static unsigned long long previousMillisWiFi = 0;

// Bluetooth
BluetoothSerial SerialBT;

WiFiClientSecure wifiClient = WiFiClientSecure();
PubSubClient mqttClient(wifiClient);

DynamicJsonDocument currentPropertiesJson(1024);
DynamicJsonDocument newPropertiesJson(1024);
const size_t capacity = JSON_ARRAY_SIZE(10) + JSON_OBJECT_SIZE(5) + 280;
DynamicJsonDocument doc(3072);

char recivedChar1[2816] =  "";
char recivedChar2[2816] = "";

void callback(char* topic, byte* payload, unsigned int length) {
  // Not needed for this example
}

// void callback(String &topic, String &payload) {
//   Serial.println("incoming: " + topic + " - " + payload);

// //  StaticJsonDocument<200> doc;
// //  deserializeJson(doc, payload);
// //  const char* message = doc["message"];
// }

void reconnect() {
  while (!mqttClient.connected()) {
    Serial.println("Reconnecting to MQTT broker...");
    if (mqttClient.connect(THINGNAME)) {
      Serial.println("Connected to MQTT broker");
    } else {
      Serial.print("Failed, rc=");
      Serial.print(mqttClient.state());
      Serial.println(" Retrying in 5 seconds...");
      delay(5000);
    }
  }
}

void btCallback(esp_spp_cb_event_t event, esp_spp_cb_param_t *param) {

  Serial.print("BT Callback Event: ");
  Serial.println(event);

  if (event == ESP_SPP_SRV_OPEN_EVT) {

    if (SerialBT.hasClient() == 1)
    {
    }
  }
  else if (event == ESP_SPP_DATA_IND_EVT) {
    btCmdRxCbFlag = true;
  }
  else if (event == ESP_SPP_CLOSE_EVT)
  {
    if (SerialBT.hasClient() == 0)
    {
    }
  }
}

void initBT() {
  if (!SerialBT.begin(deviceId)) {
    Serial.println("An error occurred initializing Bluetooth");
    ESP.restart();
  } else {
    //    SerialBT.setPin("LOLITSBP");
    Serial.println("Bluetooth initialized");
  }

  SerialBT.register_callback(btCallback);
  Serial.println("The device started, now you can pair it with bluetooth");
}

void setup() {
  Serial.begin(115200);
  
  Serial.begin(115200);
  Serial2.begin(115200, SERIAL_8N1, RXD2, TXD2);

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
}

String bluetoothReadLine() {
  String text_received = "";
  while (SerialBT.available())
  {
    byte r = SerialBT.read();
    if (r != 13 && r != 10 && char(r) != '\0')
      text_received = text_received + char(r);
  }
  return text_received;
}

void loop() {

  currentMillis = millis();
  if(currentMillis - previousMillisWiFi > 500)
  {
    previousMillisWiFi = currentMillis;
    static int oldStatusWiFi = 6;
    static int oldStatusMQTT;
    // WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    if(WiFi.status() != WL_CONNECTED) {
      Serial.println(".");
      oldStatusWiFi = WL_DISCONNECTED;
      oldStatusMQTT = -1;
    }

    if(WiFi.status() == WL_CONNECTED && oldStatusWiFi == WL_DISCONNECTED) {
    oldStatusWiFi = true;
    Serial.println("Connected to WiFi");
    oldStatusWiFi = WL_CONNECTED;

    mqttClient.setServer(AWS_IOT_ENDPOINT, 8883);
    mqttClient.setCallback(callback);

    wifiClient.setCACert(AWS_CERT_CA);
    wifiClient.setCertificate(AWS_CERT_CRT);
    wifiClient.setPrivateKey(AWS_CERT_PRIVATE);
    oldStatusMQTT = 0;
    }

    if(oldStatusWiFi == WL_CONNECTED && oldStatusMQTT == 0){
        Serial.println("Connecting to MQTT broker...");
        if (mqttClient.connect(THINGNAME)) {
          Serial.println("Connected to MQTT broker");
          oldStatusMQTT = 1;
          initBT();
        } else {
          Serial.print("Failed, rc=");
          Serial.println(" Retrying in 5 seconds...");
          // delay(500);
        }
    }

    if(oldStatusWiFi == WL_CONNECTED && oldStatusMQTT == 1){
        mqttClient.loop();
      }
  }

  if (btCmdRxCbFlag == true)
  {
    receivedBluetooth = "";
    receivedBluetooth = bluetoothReadLine();
    btCmdRxCbFlag = false;
  }

  if (currentMillis - previousMillis >= 5000)
  {
    if (mqttClient.connected())
        {
          StaticJsonDocument<200> docLocal;
          docLocal["dev_id"] = 9175021696;
          docLocal["heap"] = ESP.getFreeHeap();;
          docLocal["esp_temperature"] = temperatureRead();
          String controllerHeap = String();
          serializeJson(docLocal, controllerHeap);
          char controllerHeapChar[256];
          controllerHeap.toCharArray(controllerHeapChar, (controllerHeap.length()) + 1);
          mqttClient.publish("ranjit/garava/esp32/waterTank/publish", controllerHeapChar);
        }
    // save the last time you blinked the LED
    previousMillis = currentMillis;
  }
}
```

### Debug Message

```plain
.
.
Connected to WiFi
Connecting to MQTT broker...
Connected to MQTT broker
Bluetooth initialized
The device started, now you can pair it with bluetooth
BT Callback Event: 0
BT Callback Event: 28

assert failed: vQueueDelete queue.c:2131 (pxQueue)


Backtrace: 0x40083695:0x3fff51d0 0x400930d1:0x3fff51f0 0x40098b3d:0x3fff5210 0x400944ee:0x3fff5340 0x40122d35:0x3fff5360 0x40121c74:0x3fff5380 0x40121cc2:0x3fff53a0 0x4010b497:0x3fff53c0 0x4010ce2a:0x3fff53f0 0x4010d094:0x3fff5410 0x4013f97d:0x3fff5450 0x4010e152:0x3fff54b0 0x4012288f:0x3fff54d0




ELF file SHA256: b384bb747de10cbb

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
```

### Other Steps to Reproduce

The mentioned DynamicJsonDocument size is required to deserialize the data coming from other devices.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment] 2023-07-20 22:51
@ranjitlawand - I have tested it using Arduino Core 2.0.10, not the 2.0.7.
 
Right after connecting the ESP32 to my smartphone using the BT/SSP, I get an error related to lack of RAM and the WiFi is disconnected. 
It tries to connect to WiFi again but it fails.

I can send data using the Bluetooth from my smatphone to the ESP32 (`BT Callback Event: 30`), but the SSL can't recover...
```
[ 53795][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():264]: (-32512) SSL - Memory allocation failed
[ 53795][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -32512
```
 
### Therefore, the issue is that the application is consuming too much HEAP and it fails.
### It may need some sort of "memory optimization"...

```
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
.
.
Connected to WiFi
Connecting to MQTT broker...
The client esp32-client-78:E3:6D:CD:06:A8 connects to the public mqtt broker
Connected to MQTT broker
[  3324][I][BluetoothSerial.cpp:683] _init_bt(): device name set

Bluetooth initialized
The device started, now you can pair it with bluetooth
[  3324][I][BluetoothSerial.cpp:263] esp_spp_cb(): ESP_SPP_INIT_EVT
[  3334][I][BluetoothSerial.cpp:270] esp_spp_cb(): ESP_SPP_INIT_EVT: slave: start
BT Callback Event: 0
[  3353][I][BluetoothSerial.cpp:571] esp_bt_gap_cb(): ESP_BT_GAP_CONFIG_EIR_DATA_EVT: stat:0 num:4
[  3354][I][BluetoothSerial.cpp:397] esp_spp_cb(): ESP_SPP_START_EVT
BT Callback Event: 28
[ 20967][I][BluetoothSerial.cpp:587] esp_bt_gap_cb(): ESP-BT_GAP_* unknown message: 16
[ 37041][W][WiFiGeneric.cpp:1057] _eventCallback(): Reason: 200 - BEACON_TIMEOUT
[ 37047][E][ssl_client.cpp:37] _handle_error(): [send_ssl_data():382]: (-78) UNKNOWN ERROR CODE (004E)
.
.
.
.
.
[ 39458][W][WiFiGeneric.cpp:1057] _eventCallback(): Reason: 201 - NO_AP_FOUND

The client esp32-client-78:E3:6D:CD:06:A8 connects to the public mqtt broker
[ 53795][E][ssl_client.cpp:37] _handle_error(): [start_ssl_client():264]: (-32512) SSL - Memory allocation failed
[ 53795][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -32512
failed with state -2

BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30

```

**Comment by SuGlider** [comment] 2023-07-20 22:56
You may try using some TCP/IP service instead of Classic Bluetooth SSP.... like HTTP for what ever your application may need it.

**Comment by SuGlider** [comment] 2023-07-21 00:57
@ranjitlawand - This information may be of your interest: When I use the ESP32-WROVER with PSRAM, everything works fine... Part of the WiFi and BT buffers are allocated automatically in the PSRAM, therefore, it doesn't fail.

`BT Callback Event: 30` message is when I send data from my smartphone to the ESP32-WROVER using BT.

Logs:
```
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13924
ho 0 tail 12 room 4
load:0x40080400,len:3600
entry 0x400805f0
[   469][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
Starting WiFi...
.
.
.
.
.
.
.
[  5662][W][WiFiGeneric.cpp:1057] _eventCallback(): Reason: 2 - AUTH_EXPIRE
Connected to WiFi
Connecting to MQTT broker...
The client esp32-client-78:E3:6D:CD:06:A8 connects to the public mqtt broker
Connected to MQTT broker
[ 11666][I][BluetoothSerial.cpp:571] esp_bt_gap_cb(): ESP_BT_GAP_CONFIG_EIR_DATA_EVT: stat:0 num:4
[ 11666][I][BluetoothSerial.cpp:683] _init_bt(): device name set
[ 11668][I][BluetoothSerial.cpp:263] esp_spp_cb(): ESP_SPP_INIT_EVT
Bluetooth initialized
[ 11676][I][BluetoothSerial.cpp:270] esp_spp_cb(): ESP_SPP_INIT_EVT: slave: start
The device started, now you can pair it with bluetooth
BT Callback Event: 0
[ 11701][I][BluetoothSerial.cpp:571] esp_bt_gap_cb(): ESP_BT_GAP_CONFIG_EIR_DATA_EVT: stat:0 num:4
[ 11701][I][BluetoothSerial.cpp:397] esp_spp_cb(): ESP_SPP_START_EVT
BT Callback Event: 28
[ 16645][I][BluetoothSerial.cpp:278] esp_spp_cb(): ESP_SPP_SRV_OPEN_EVT: 0
BT Callback Event: 34
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
BT Callback Event: 30
[ 28763][I][BluetoothSerial.cpp:583] esp_bt_gap_cb(): ESP_BT_GAP_MODE_CHG_EVT: mode: 2
```

**Comment by ranjitlawand** [comment] 2023-07-24 07:14
Hello @SuGlider,

Thanks for the quick response. 

I do understand the code needs optimization but I do need bigger JSON buffers to deserialize and serialize JSONs. 

The current hardware which I'm using does not have PSRAM. Is it possible to get the setup working with the above code?

**Comment by SuGlider** [comment] 2023-07-24 11:25
>The current hardware which I'm using does not have PSRAM. Is it possible to get the setup working with the above code?

I tried the above code without PSRAM and it fails exactly as you said.

With PSRAM it runs fine. I tested it with a ESP32-WROVER-E that has 4MB SPRAM.
When the SoC has PSRAM, part of the `maloc()` (higher than 4KB block) calls will go to the PSRAM instead of HEAP.

**Comment by VojtechBartoska** [comment] 2023-10-04 14:32
Closing this as answered.

**Closed by VojtechBartoska** 2023-10-04 14:32 UTC
Labels: Area: BT&Wifi, Type: Question, Status: Solved
