### ISSUE TITLE
How can I program the ESP-WROOM-32 with LabVIEW ??

### ISSUE THREAD

**Issue by Abdulaziz95** [espressif/arduino-esp32#1151] opened 2018-02-26 09:45 UTC
### Hardware:
Board:							?ESP32 Dev Module?
Core Installation/update date:			?11/jul/2017?
IDE name:							?Arduino IDE? ?Platform.io? ?IDF component?
Flash Frequency:					?40Mhz?
Upload Speed:						?115200?

### Description:
How can I program the ESP-WROOM-32 with LabVIEW ??

**Comment by lbernstone** [comment] 2018-02-26 15:52
You need to explain what you are hoping to achieve. ESP32 has a standard serial and UART interface, so anything designed to collect data from another Arduino device and visualize it in Labview should be fairly interoperable (not all arduino libraries will work with ESP32).  If you want LabView to control an ESP32, then you will need to figure out a whole lot of integrations which are way beyond the scope of a one sentence question.

**Comment by XYZVector** [comment] 2018-03-02 16:45
You cannot do this.. Sorry but this is a C/C++ environment you are in. Look in google to see if this can be done.

**Comment by everslick** [comment] 2018-04-19 12:18
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 12:18 UTC
