### ISSUE TITLE
Can't connect to wifi access point with space in SSID

### ISSUE THREAD

**Issue by GeeF** [espressif/arduino-esp32#836] opened 2017-11-15 13:35 UTC
### Hardware:
Board:							ESP32 Dev Module
Core Installation/update date:			14/nov/2017
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
Connection to a WiFi access point fails, if the SSID contains a space.

### Sketch:
use the example client sketch

**Comment by me-no-dev** [comment] 2017-11-16 12:42
I don't think that SSID should contain space at all

**Comment by GeeF** [comment] 2017-11-16 14:19
Have a look at standards.ieee.org/getieee802/download/802.11-2012.pdf
Section 8.4.2.2: "The length of the SSID field is between 0 and 32 octets".
So it is basically just a 32 byte buffer that can be interpreted as UTF-8.

If it can't/shouldn't/wouldn't work for the esp32 implementation, it should at least be documented somewhere so people don't run into it.

**Comment by me-no-dev** [comment] 2017-11-16 14:48
all in all, Arduino calls the API exposed in IDF. Arduino itself does not limit you to "no space in name". I will try to contact the WiFi engineers and see what they can do.

**Comment by GeeF** [comment] 2017-11-27 16:38
Thanks :)

**Comment by zhangyanjiaoesp** [comment] 2017-12-01 06:47
@GeeF Arduino calls the API exposed in IDF. Arduino itself does not limit you to "no space in name". So I tested in IDF,  I can connect to a WiFi access point successfully, if the SSID contains a space.

**Comment by GeeF** [comment] 2017-12-01 13:22
I have just tried again with a different AP and it works. Seems to be something fishy about the other AP I’ve been using. 
Sorry to have wasted your time

**Comment by Fitap** [comment] 2018-03-25 21:27
Hi, I was the same issue like @GeeF and in my case I have setup the tkip flag in wireless security profile.
May helps some one.

Regards.

**Comment by everslick** [comment] 2018-04-19 07:54
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 07:54 UTC
