### ISSUE TITLE
ESP32 - BLE Communication - Connection issues with different frequency value from crystal oscillator 

### ISSUE THREAD

**Issue by arunprakash2611** [espressif/arduino-esp32#6100] opened 2022-01-05 10:41 UTC
### Related area

Bluetooth 

### Hardware specification

ESP32 WROOM - 32U

### Is your feature request related to a problem?

Hi,

Thanks for your time,

We are working on multiple ESP32 module to finalize the one of bluetooth related project.

while working with multiple ESP32 development kit, we facing different result from different board instead one unique results since we are using same firmware all the hardware and same scenarios 

Case 1 - While checking some of the board with own developed software application (both mobile as well as windows) - its working fine
Case 2 - But some of the board, working fine on mobile application alone instead of windows also

While checking in deeply, we found different kind of frequency available for different boards like 39.9999 MHz and 39.9969 MHz, 

So exact frequency required to connect properly for Bluetooth communication? And what is the exact frequency to operate the bluetooth communication

Note : I mean 40 Mhz is mandatory for BLE Communication? or what is the operating frequency value ?

![IMG-20220105-WA0000](https://user-images.githubusercontent.com/89899208/148203604-7cf91af0-db7c-4b8f-9d80-55cb6b8dcdbb.jpg)
![IMG-20220105-WA0001](https://user-images.githubusercontent.com/89899208/148203612-270ce4d5-e7ba-45ad-92d3-f050fbff865b.jpg)
 
 

### Describe the solution you'd like

Need a exact or particular range of crystal frequent to operate BLE communication properly

**Comment by h2zero** [comment] 2022-01-14 05:03
BLE operates on the same frequency as WiFi, in the 2.4ghz range. I highly doubt the 3khz difference you're seeing from the clock between boards is the cause of your issue.

**Comment by chegewara** [comment] 2022-01-14 05:06
@h2zero actually it may be the problem, because ble specs has more strict requirements about +/-ppm.
I would ask this on esp-idf as it is not related to arduino and you can find nore educated and experienced expert in there.

**Comment by h2zero** [comment] 2022-01-14 14:25
@chegewara Yes, you're correct. I was too tired to do the math but it looks like the xtal in this case is -75ppm, most specs I have seen call for +/- 40-60ppm.

**Comment by chegewara** [comment] 2022-01-14 15:54
oh, i didnt mean you, i was tellin about myself not being experienced and educated, sorry for misunderstanding.

**Comment by h2zero** [comment] 2022-01-14 16:04
>oh, i didnt mean you, i was saying about myself not being experienced and educated, sorry for misunderstanding.

Lol I didn't take it that way, but you're still correct anyway :)

**Comment by VojtechBartoska** [comment] 2022-04-11 14:20
Hello, is this still valid?

**Comment by VojtechBartoska** [comment] 2022-05-04 19:32
Closing as expired due to no answer.

If needed, reopen the issue.

Thanks for understanding.

**Closed by VojtechBartoska** 2022-05-04 19:32 UTC
Labels: Type: Feature request, Resolution: Awaiting response
