### ISSUE TITLE
Sketch help

### ISSUE THREAD

**Issue by folny** [espressif/arduino-esp32#1041] opened 2018-01-28 21:14 UTC
Hello friends

Can anyone advise me how to edit this sketch to work with ESP32 in advance thanks for your reply.

https://github.com/dc42/arduino/blob/master/MetalDetector/MetalDetector.ino

**Comment by folny** [comment] 2018-02-06 20:48
Hello friends

So nobody can tell me how to compile this code for ESP ? please advise the biggest problem is with this frequent code.

ISR(TIMER1_OVF_vect)
{
  ++ticks;
  uint8_t ctr = TCNT0;
  int16_t val = (int16_t)(uint16_t)ADCH;    // only need to read most significant 8 bits
  if (ctr != ((lastctr + 1) & 7))
  {
    ++misses;
  }
  lastctr = ctr;
  int16_t *p = &bins[ctr & 3];
  if (ctr < 4)
  {
    *p += (val);
    if (*p > 15000) *p = 15000;
  }
  else
  {
    *p -= val;
    if (*p < -15000) *p = -15000;
  } 
  if (ctr == 7)
  {
    ++numSamples;
    if (numSamples == numSamplesToAverage)
    {
      numSamples = 0;
      if (!sampleReady)      // if previous sample has been consumed
      {
        memcpy((void*)averages, bins, sizeof(averages));
        sampleReady = true;
      }
      memset(bins, 0, sizeof(bins));
    }
  }
}

**Comment by everslick** [comment] 2018-04-19 11:28
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 11:28 UTC
