### ISSUE TITLE
HTTP Advanced Authentication (Digest) fails!

### ISSUE THREAD

**Issue by Al-Imran** [espressif/arduino-esp32#4943] opened 2021-03-14 09:57 UTC
### Hardware:
Board:							ESP32 Dev Module (ESP32-CAM)
Core Installation version:			1.0.5
IDE name:						Visual Studio Code
Flash Frequency:					80Mhz
PSRAM enabled:                                     no
Upload Speed:					921600
Computer OS:                                        Windows 10

### Description:
The example provided for the **WebServer** library, namely _HTTP Advanced Authentication_ fails to authenticate the entered credentials (username and password) when 

`server.requestAuthentication(DIGEST_AUTH, www_realm, authFailResponse);`

is used. It works fine when `BASIC_AUTH` is used instead of `DIGEST_AUTH`.

### Sketch: 
Find the example here: [https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer/examples/AdvancedWebServer](url)

### Debug Messages:
```
[V][WebServer.cpp:291] handleClient(): New client
[V][Parsing.cpp:113] _parseRequest(): method: GET url: / search: 
[V][Parsing.cpp:219] _parseRequest(): headerName: Host
[V][Parsing.cpp:220] _parseRequest(): headerValue: esp-32.local
[V][Parsing.cpp:219] _parseRequest(): headerName: Connection
[V][Parsing.cpp:220] _parseRequest(): headerValue: keep-alive
[V][Parsing.cpp:219] _parseRequest(): headerName: Cache-Control
[V][Parsing.cpp:220] _parseRequest(): headerValue: max-age=0
[V][Parsing.cpp:219] _parseRequest(): headerName: Authorization
[V][Parsing.cpp:220] _parseRequest(): headerValue: Digest username="admin", realm="AuthRealm", nonce="85a00f44039bcd6c4a568e3987e427d1", uri="/", response="654bbf08ab51d8ee6ff4c1bad07da387", opaque="9cca6efbf86bd3acd8d80ae2c9cb2a87", qop=auth, nc=00000002, cnonce="414f50ee2fddc370"
[V][Parsing.cpp:219] _parseRequest(): headerName: DNT
[V][Parsing.cpp:220] _parseRequest(): headerValue: 1
[V][Parsing.cpp:219] _parseRequest(): headerName: Upgrade-Insecure-Requests
[V][Parsing.cpp:220] _parseRequest(): headerValue: 1
[V][Parsing.cpp:219] _parseRequest(): headerName: User-Agent
[V][Parsing.cpp:220] _parseRequest(): headerValue: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 OPR/74.0.3911.203
[V][Parsing.cpp:219] _parseRequest(): headerName: Accept
[V][Parsing.cpp:220] _parseRequest(): headerValue: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
[V][Parsing.cpp:219] _parseRequest(): headerName: Accept-Encoding
[V][Parsing.cpp:220] _parseRequest(): headerValue: gzip, deflate
[V][Parsing.cpp:219] _parseRequest(): headerName: Accept-Language
[V][Parsing.cpp:220] _parseRequest(): headerValue: en-US,en;q=0.9
[V][Parsing.cpp:247] _parseArguments(): args: 
[V][Parsing.cpp:230] _parseRequest(): Request: /
[V][Parsing.cpp:231] _parseRequest():  Arguments: 
[V][WebServer.cpp:165] authenticate(): username="admin", realm="AuthRealm", nonce="85a00f44039bcd6c4a568e3987e427d1", uri="/", response="654bbf08ab51d8ee6ff4c1bad07da387", opaque="9cca6efbf86bd3acd8d80ae2c9cb2a87", qop=auth, nc=00000002, cnonce="414f50ee2fddc370"
[V][WebServer.cpp:193] authenticate(): Hash of user:realm:pass=a4b486674763c506e39285f29f658eff
[V][WebServer.cpp:206] authenticate(): Hash of GET:uri=71998c64aea37ae77020c49c00f73fa8
[V][WebServer.cpp:213] authenticate(): The Proper response=be48fe779ae1dc96a49b00985c415dc8

```
### Diagnosis:
It is evident (from the verbose debug outputs) that the the response check fails. In other words,
**Received:** `654bbf08ab51d8ee6ff4c1bad07da387`
**Expected:** `be48fe779ae1dc96a49b00985c415dc8`

I am guessing it is at this part 
`if(_response == _responsecheck){
        authReq = "";
        return true;
      }`
of _WebServer.cpp_, line _215_ where it fails.

I can confirm that the expected MD5 digest is in fact `H(H(username:realm:password):nonce:H(uri))`, where `H` is the MD5 Hash function and others are self explanatory. Now the only unknown is the received digest. If we could only see the original string of the received response message. So far I have tried this on Chrome and Opera browsers thinking it might have something to do with the browser itself(!?!?). 

So, what is causing this issue and how do we get rid of it? Thanks in advance.

**Comment by me-no-dev** [comment] 2021-03-16 10:11
hmmm... I can not reproduce the problem. Auth seems to work fine on my end. Can you try to test against the current `master` of this repo?

**Comment by v-c** [comment] 2021-03-18 22:28
I am also able to reproduce the above issue with a Wemos Battery board like [this](https://www.aliexpress.com/item/32819459737.html). The sketch I used to reproduce the problem is [here](https://github.com/Hieromon/AutoConnect/issues/315#issuecomment-799987660). 

I tried this sketch with Arduino IDE and PlatformIO with Arduino framework.

**Comment by me-no-dev** [comment] 2021-03-19 00:12
@v-c I added the suggested fix from the post above the sketch you pointed at. Commit is here: https://github.com/espressif/arduino-esp32/commit/2d3c57635d6ef7d180a1e292e5e6d8b467228afa

Is there any chance that you can test against current master of this repo? I think PIO has that option as well.

**Comment by v-c** [comment] 2021-03-20 06:35
I tested the fix with ESP8266 and DIGEST_AUTH works as expected.

**Comment by me-no-dev** [comment] 2021-03-20 09:32
great :) closing now!

**Closed by me-no-dev** 2021-03-20 09:32 UTC
