### ISSUE TITLE
mDNS_Web_Server.ino: Invalid service type

### ISSUE THREAD

**Issue by antonio-fiol** [espressif/arduino-esp32#520] opened 2017-07-17 12:24 UTC
mDNS_Web_Server.ino includes the line:
`    MDNS.addService("http", "tcp", 80);`
This causes avahi-browse on Linux to fail with "Invalid service type". Changing that line to the following fixes the issue.
`    MDNS.addService("_http", "_tcp", 80);`

**Comment by sansillusion** [comment] 2017-08-29 03:17
Thanks ! Now I need to know how to get chrome to work with it like my D-link range boosters
ie: open http://lumiere.local
but it does not work.
In ZeroConf Browser for android my D-Links have a extra listing under (_DHNAP) ?
is _DHNAP what's needed and does it exist under esp32 ?

**Comment by antonio-fiol** [comment] 2017-08-29 06:55
@sansillusion as far as I can tell, you do actually not need any service entry for a browser to be able to open said URL. The service entry is only for discoverability.
To set the host name and make it available on the network for mDNS resolution, in the same example file, the line
```if (!MDNS.begin("esp32")) {```
allows you to find it on esp32.local.
I imagine you already changed that to
```if (!MDNS.begin("lumiere")) {```

**Comment by sansillusion** [comment] 2017-08-29 08:45
@antonio-fiol Yes I did already changed it.
I kind of got it working by installing Apple Bonjour V3 (extracted from iTunes installer) but it leaves me confused because : 
1: My D'Link range extenders did not need Bonjour installed to work
2: It does not work with Edge only in chrome (perfect for me but some people use Edge)

But at least it somwhat works now

**Comment by antonio-fiol** [comment] 2017-08-29 09:02
Sorry, I can't help further: I do not use Windows so I never had to fiddle
with mDNS on Windows.

**Comment by sansillusion** [comment] 2017-08-29 18:00
@antonio-fiol  Thanks a lot, at least it somewhat works now.
I guess the library works with the Bonjour protocol and windows and chrome must have a different implementation of the mDNS protocol.

**Comment by me-no-dev** [comment] 2017-08-30 05:31
new mdns is coming soon ;) it follows all official rules so it should be fine.

**Comment by sansillusion** [comment] 2017-08-30 18:01
@me-no-dev Thank-you for the info !!! You rock !

**Comment by copercini** [comment] 2018-02-13 21:05
@sansillusion is it working with the new mdns?

**Comment by sansillusion** [comment] 2018-02-13 21:38
I cant test right now, it works with apple bonjour installed. But I hope it does without having to install apple bonjour like for the esp8266.

I will try later tonight to see and report back.

**Comment by sansillusion** [comment] 2018-02-13 21:58
Still seem the same here, Will not wirk without installing apple Bonjour V3, it does not show up in chrome MDNS browser nor in edge

**Comment by sansillusion** [comment] 2018-02-22 05:32
I seem to have had some weird issue with my setup.
I noticed that even if git GUI sometimes had some updates when doing the update procedures, I had many different files (old versions) than what is shown on GitHub. So I manually downloaded the repo and copied it over my (documets/arduino/hardware/espressif/esp32) folder, than ran get.exe and "$ git submodule update --init --recursive" in git bash and then recompiled my code ( there is a warning about invalid BLE library wich I dont use anyway) and my code jumped from around 30% of program storage to 62% but everything seems to work better even mDNS !!! it shows up in chrome mdns browser plugin YAY !

I guess I will have to cleanup my PC and redo the whole esp32 setup.

**Comment by everslick** [comment] 2018-04-19 06:54
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 06:54 UTC
Labels: awaiting response
