### ISSUE TITLE
interrupt problem

### ISSUE THREAD

**Issue by savagerex** [espressif/arduino-esp32#8416] opened 2023-07-17 06:30 UTC
### Board

ESP32 S3

### Device Description

Sensor - IIS3DWB
Flash

### Hardware Configuration

NONE

### Version

v2.0.9

### IDE Name

Arduino

### Operating System

Windows 11

### Flash frequency

80M

### PSRAM enabled

no

### Upload speed

921600

### Description

when i use interrupt.

Sometimes the value "Isrk" will overflow.

the code as below.

void IRAM_ATTR IntOneIsr() {
     //DryFlag = 1;    
     //DataReady = true; 
       IsrK++;
       if(IsrK==6)
       {
         IsrK=0;
         DataReady = true;
       } 
     
}

### Sketch

```cpp
#include "SPI.h"
#include "SPIFFS.h"
#include <SerialFlash.h>
#include "BoardConfig.h"
#include "Sensor.h"
#include "IIS3DWB.h"
#include <WiFi.h>
#include <MQTT.h>


const char* ssid = "ASUS_24";     //SW1-WIFI6   ASUS-38   oppo          ASUS_24
const char* pass = "12345678";   //wireless    12345678   1234567890    12345678

const char* mqtt_server = "192.168.51.111";   //broker.emqx.io  192.168.50.128
//const char *topic = "DataTopic";
const char *topic = "1/report";
const char *mqtt_username = "emqx";
const char *mqtt_password = "public";

WiFiClient net;
MQTTClient client(487000);   //2000


SPIClass SPI2(HSPI);


const char Version[]="1.0.0";
const char CompileDate[]= __DATE__ " " __TIME__;
#define CSPIN    10

uint8_t Ascale = AFS_2G;

float aRes;                              // scale resolutions per LSB for the accel 
float accelBias[3] = {0.0f, 0.0f, 0.0f}; // offset biases for the accel 
int16_t IIS3DWBData[4] = {0};            // Stores the 16-bit signed sensor output
uint8_t IIS3DWBRawData[6] = {0};            // Stores the 16-bit signed sensor output
int16_t destination[3];
float ax, ay, az, accelTemp;             // variables to hold latest accel data values 
uint8_t IIS3DWBstatus;
//long values[40];
uint8_t ui8txLogBuf[20];
uint32_t i, j, k, m, n;
uint32_t IsrK;
int DryFlag = 1;
int FileWriteFlag = 0;
int FileReadFlag = 0;
int packet_counter = 1;

unsigned long StartTime;
unsigned long EndTime;

volatile bool DataReady = false;

#define PACKAGE 600       
#define TotalData  14850     //6*27000*11/120 =14850 //6*27000*11        
#define ReadTotalData  99    //297 //297000

//uint8_t DataBufWrite[125];  
//uint8_t DataBufRead[18500];
uint8_t* DataBufWrite;  
uint8_t* DataBufRead;


IIS3DWB IIS3DWB(CSPIN);

unsigned long StartTestTime;
unsigned long EndTestTime;

unsigned long StartWriteTime;
unsigned long EndWriteTime;


// Pins used for the connection with the sensor
const int CHIP_SELECT_PIN = 10;  //7

SerialFlashFile flashFile;

uint8_t ascii_trans(uint8_t ui8Code) {
  if((ui8Code == 0 || ui8Code > 0) && ui8Code <= 9){
    ui8Code += 48;  //0x30;
  }else if(ui8Code >= 10 && ui8Code <= 15){
    ui8Code += 55;  //0x37;
  }
  return ui8Code;
}

void IRAM_ATTR IntOneIsr() {
     //DryFlag = 1;    
     //DataReady = true; 
       IsrK++;
       if(IsrK==6)
       {
         IsrK=0;
         DataReady = true;
       } 
     
}

void connect() {
  Serial.print("checking wifi...");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(1000);
  }

  Serial.print("\nconnecting...");

  while (!client.connect("arduino", "public", "public")) {
    Serial.print(".");
    delay(1000);
  }

  Serial.println("\nconnected!");

  
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  pinMode(led1GPin, OUTPUT);
  pinMode(led2GPin, OUTPUT);
  pinMode(SensorPowerPin, OUTPUT);
  digitalWrite(SensorPowerPin, HIGH);
  delay(15);
  
  //SPI1.begin(GPIO_OUTPUT_SCLK, GPIO_INPUT_MISO, GPIO_OUTPUT_MOSI, GPIO_OUTPUT_CS);    //move to IIS3DWB.cpp
  
  //SPI.beginTransaction(SPISettings(spiClk, MSBFIRST, SPI_MODE0));

  DataBufWrite = (uint8_t*)ps_calloc(486050, sizeof(uint8_t));   //6 * 27000 * 3 = 486000
  DataBufRead = (uint8_t*)ps_calloc(486050, sizeof(uint8_t));

//  delay(10);
//    WiFi.begin(ssid,pass);
//
//    Serial.print("Connecting.");
//    while(WiFi.status() != WL_CONNECTED) {
//        Serial.print(".");
//        delay(500);
//    }
//
//    Serial.print("WiFi connected - IP address: ");
//    Serial.println(WiFi.localIP());
//
//
//    client.begin(mqtt_server, net);
//
//
//
//  Serial.print("\nconnecting...");
//  while (!client.connect("arduino", "public", "public")) {
//    Serial.print(".");
//    delay(1000);
//  }
//
//  Serial.println("\nconnected!");
 
  // Initalize the  data ready and chip select pins:
  pinMode(CSPIN, OUTPUT);
  digitalWrite(CSPIN, HIGH);

  Serial.println("IIS3DWB accel...");
  uint8_t c = IIS3DWB.getChipID();  // Read CHIP_ID register for IIS3DWB
  Serial.print("IIS3DWB "); Serial.print("I AM "); Serial.print(c, HEX); Serial.print(" I should be "); Serial.println(0x7B, HEX);
  Serial.println(" ");

  if(c == 0x7B) // check if all SPI sensors have acknowledged
  {
   Serial.println("IIS3DWB is online...");  
   Serial.println(" ");

   // reset IIS3DWB to start fresh
   IIS3DWB.reset();  

   // get accel sensor resolution, only need to do this once
   aRes = IIS3DWB.getAres(Ascale);

   IIS3DWB.selfTest();

   IIS3DWB.init(Ascale); // configure IIS3DWB  

   IIS3DWB.offsetBias(accelBias);
   Serial.println("accel biases (mg)"); Serial.println(1000.0f * accelBias[0]); Serial.println(1000.0f * accelBias[1]); Serial.println(1000.0f * accelBias[2]);
   Serial.println(" ");
   delay(1000); 
   
   
  }
  else 
  {
  if(c != 0x6A) Serial.println(" IIS3DWB not functioning!"); 
  while(1){};
  }

  // Give the sensor time to set up:
  delay(100);
  attachInterrupt(INTONE, IntOneIsr, RISING);

  if (!SPIFFS.begin(true)) {
    Serial.println("An Error has occurred while mounting SPIFFS");
    return;
  }

  xTaskCreatePinnedToCore(taskOne, "TaskOne", 30000, NULL, 2, NULL, 0);
  xTaskCreatePinnedToCore(taskTwo, "TaskTwo", 30000, NULL, 2, NULL, 1);

  //SPIFFS.format();
  Serial.println("Setup Finish");

}

void taskOne( void * parameter ) {
   disableCore0WDT();

   File file = SPIFFS.open("/test.txt", FILE_WRITE);
  
    if (!file) {
      Serial.println("There was an error opening the file for writing");
      return;
    }

   
   for (;;) {

        
        if (DataReady) {
           DataReady = false;
           if (n == 0) {
            StartTestTime = millis();
           }
           
          //IIS3DWB.readAccelData(IIS3DWBData);
          IIS3DWB.readAccelRawData(IIS3DWBRawData);

          for(i = 0; i < 6; i++) {
              DataBufWrite[k] = IIS3DWBRawData[i];
              k+=1;
          }
    
          n++; 
          //m++;

          if(k==72000)   //486000
          {
             Serial.println("3 Sec Data");

             char *DataBuf = (char*)DataBufWrite;
             //client.publish(topic, DataBuf, PACKAGE+2, false, 0);
             //bool PubData = client.publish(topic, DataBuf, 486000, false, 0);  //18000 //6000
             //Serial.println(PubData);
             
//             file.write(DataBufWrite, 486000); 
//             file.close();
             FileReadFlag = 0;
             k=0;
             while (1) {
                delay(1000);
                digitalWrite(led1GPin, HIGH);
                delay(1000);
                digitalWrite(led1GPin, LOW);
              }
          }

          
            
//            if(m == 81000)
//            {
//              Serial.println("3 Sec Data");
//              while (1) {
//                delay(1000);
//                digitalWrite(led1GPin, HIGH);
//                delay(1000);
//                digitalWrite(led1GPin, LOW);
//              }
//            }
    
            if (n == 4000) {     //26667
                EndTestTime = millis();
                Serial.print("**************SPI Sensor Time*************");
                Serial.println(EndTestTime - StartTestTime);
                n = 0;
            }
          
         }

       
   }
   vTaskDelete( NULL );
}

void taskTwo( void * parameter ) {
   disableCore1WDT();
   
   for (;;) {

        if (FileReadFlag == 1) {
            FileReadFlag = 0;
            
            File file = SPIFFS.open("/test.txt", FILE_READ);
            
            file.read(DataBufRead, 486000);

            //Serial.write(DataBufRead, 486000);

                client.loop();  
              
                if (!client.connected()) {
                  connect();
                }

            char *DataBuf = (char*)DataBufRead;
            //client.publish(topic, DataBuf, PACKAGE+2, false, 0);
            bool PubData = client.publish(topic, DataBuf, 486000, false, 0);  //18000 //6000
            Serial.println(PubData);

            Serial.println("MQTT Finish");
            file.close();
            //file.remove("test.txt");

             while (1) {
                delay(1000);
                digitalWrite(led2GPin, HIGH);
                delay(1000);
                digitalWrite(led2GPin, LOW);
              }
            
        }
        delay(100);
   }
   vTaskDelete( NULL );
}

void loop() {
  
}

//void loop() {
//  
//
//
//         if(DryFlag == 1) {
//          DryFlag = 0;
//
//         IIS3DWB.readAccelRawData(IIS3DWBRawData); 
//
//
//          for(i = 0; i < 6; i++) {
//            ui8txLogBuf[j] = ascii_trans((IIS3DWBRawData[i] >> 4));
//            ui8txLogBuf[j+1] = ascii_trans((IIS3DWBRawData[i] & 0x0F));
//            j+=2;
//          }
//
//          if (packet_counter < 10) {
//            Serial.write(ui8txLogBuf, 12);
//          } else if (packet_counter == 10) {
//            ui8txLogBuf[j] = '\r';
//            ui8txLogBuf[j + 1] = '\n';
//            Serial.write(ui8txLogBuf, 14); 
//            //m += 1;
//            //j = 0;
//            packet_counter = 0;
//          }
//          packet_counter++;
//          j = 0;
//
//       }
//         
//
//
//  // Next data in 100 milliseconds
//  //delay(1000);
//  //delayMicroseconds(211);   //250
//
//}
```

### Debug Message

```plain
NONE
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment] 2023-07-17 14:04
@savagerex - I'm sorry, but the issue is not clear. Please give us more details and a longer description.

In a first glance, I think that  `lsrK` shall be declared `volatile` because it is only modified inside a ISR. Marking `lsrK` as volatile, it will prevent the compiler to optimize it.

**Comment by SuGlider** [comment] 2023-07-17 14:46
Another thing would be to make sure that `lsrK` is correctly initialized.
`uint32_t IsrK = 0;`

**Comment by savagerex** [comment] 2023-07-18 03:18
ok!!  thanks.

**Comment by VojtechBartoska** [comment] 2023-08-18 13:07
Closing this as asnwered.

**Closed by VojtechBartoska** 2023-08-18 13:07 UTC
Labels: Type: Question
