### ISSUE TITLE
how to large array of bytes on flash 

### ISSUE THREAD

**Issue by Akskaypohankar** [espressif/arduino-esp32#1021] opened 2018-01-22 12:51 UTC
Please fill the info fields, it helps to get you faster support ;)

Hi,
thanks in advance for addressing this request.
We are using Arduino for programming and Sparkfun esp 32 things board for hardware.

in my code, I am receiving a large data of approximately 3kb [all hexa. bytes ] in size via a hardware serial port which I need to store and then process for further processing. because of its size, i think flash is the only place where I can store this but while using preferences library for this how can I make an array in a flash to store all this data under one variable.
please if you know any better or alternate way to solve this problem feel free to suggest

If you have a Guru Meditation Error, please decode it:
https://github.com/me-no-dev/EspExceptionDecoder

----------------------------- Remove above -----------------------------

### Hardware:
Board:                                                           sparkfun esp32 things 		
Core Installation/update date:			?11/jul/2017?
IDE name:							Arduino IDE
Flash Frequency:					?80Mhz?
Upload Speed:						?115200?

### Description:
Describe your problem here

### Sketch:
```cpp

//Change the code below by your sketch
#include <Arduino.h>

void setup() {
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by jestebanes** [comment] 2018-01-25 00:34
Hi, why don't you use a simple static or dynamic byte vector in ram, this machine is plenty of ram and you don't need to do strangers things
Another option is to use a file in the SPFISS file system, that let you manage flash as a file.
Best regards

**Comment by everslick** [comment] 2018-04-19 11:49
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 11:49 UTC
