### ISSUE TITLE
How to send an audio file to a Bluetooth Speaker

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#998] opened 2018-01-14 19:59 UTC
### Hardware:
Board:							ESP32 Dev Module?
IDE name:							Platform.io Arduino-ESP32
I need to use ESP32 to send audio file stored on a SD card to Bluetooth Speaker but I don't know how to do it using Arduino-ESP32. Using smartphone is easy just connect to Speaker and then play sound. Is it easy just like that?

**Comment by joeybab3** [comment] 2018-01-16 05:48
It's a lot more difficult than that, and as far as i know this can't be done using the arduino IDE, only the actual Espressif sdk.

**Comment by joeybab3** [comment] 2018-01-16 05:48
I've attempted this myself or at least getting audio to work on the esp32 and was able to get this example playing audio: https://github.com/MrBuddyCasino/ESP32_MP3_Decoder

**Comment by everslick** [comment] 2018-04-19 10:52
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 10:52 UTC
