### ISSUE TITLE
Unable to get gatt_client demo to work on WROVER board

### ISSUE THREAD

**Issue by ankitdaf** [espressif/arduino-esp32#452] opened 2017-06-18 06:19 UTC
Hi

I have a ESP-WROVER-KIT board and I am trying to run gatt_client demo on it. I am able to flash the code and run make monitor, and the board boots as well, but it won't scan for BLE devices. I am able to get the same code to run on the DevKitC, and it works just fine with no changes at all.

Is there a configuration specific to the WROVER-KIT that I am missing ? Or could it just be a damaged board ?

**Comment by me-no-dev** [comment] 2017-06-21 10:31
Huh? Tha is rather strange! Both boards include the same module so there is really nothing that would make BLE work on one and not the other. I also have both boards (and more) and have never had issues that will differentiate them

**Comment by everslick** [comment] 2018-04-19 06:05
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 06:05 UTC
