### ISSUE TITLE
S3 sketch fails to execute when built on Linux (Ubuntu) but executes perfectly when built on Windows. Unexpected Maker S3 boards 

### ISSUE THREAD

**Issue by Idirianuk** [espressif/arduino-esp32#6661] opened 2022-04-29 08:13 UTC
### Board

Unexpected Maker Tiny S3 (ESP32-S3FN8) and Feather S3 (ESP32-S3)

### Device Description

Bare board- nothing else attached.

### Hardware Configuration

No devices connected

### Version

v2.0.2

### IDE Name

Arduino IDE and Arduino via vs.code

### Operating System

Linux Mint (Ubuntu 20.04LTE) and Windows 10

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

Tested using 2.02 and 2.03RC1

When compiling any sketch under Linux, in all circumstances, for the UM Tiny S3, the board enters a continuous boot loop. For the UM Feather S3 board, SOME partitioning schemes will run, without boot looping.

Under Windows 10, everything compiles and loads perfectly well with no problems for either board.

For the UMFeather S3, under Linux, the schemes marked in red always fail.
For the UM Tiny S3, all schemes fail.
![schemes](https://user-images.githubusercontent.com/47950848/165906661-11938cbf-e338-443d-bf5f-e52990e80904.png)

### Sketch

```cpp
// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}
```

### Debug Message

```plain
Build:Mar 27 2021
entry 0x403b61d8
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403bb22e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x43c
load:0x403b6000,len:0xbd0
load:0x403ba000,len:0x29c8
entry 0x403b61d8
ESP-ROM:esp32s3-20210327
```

### Other Steps to Reproduce

Compile Blink sketch on Linux IDE results in failures to execute.
Compile Blink sketch on Windows IDE, results in success.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment] 2022-04-29 09:01
Is esptool.py v3.3 used? Only the v3.3 includes the needed header patching fix for the S3. Without you encounter issues with boards and partitions using a other scheme than 4MB

**Comment by Idirianuk** [comment] 2022-04-29 09:29
At this time, I have moved away from Linux and on to Windows because of these difficulties and am unable to reproduce at this time.

At the time, under Linux, I tried installing the toolchain manually AND via board manager. Both caused problems with the UM boards.

Regarding esptool 3.3, all was set up using a current toolchain as it was a brand new install of Linux. Under windows, esptool is most certainly 3.3. I have uninstalled Linux, but it is my belief that 3.3 was being used. I have to say, I cannot confirm this absolutely at this time.

It is worth mentioning that irrespective of partition scheme used, for the UM Tiny S3, no partition scheme worked at all.

_I realise this is unhelpful_. By reporting this issue, I was hoping to provide a service to the community and help with the improvement of the toolchain. It is worth stating that I am not a technical expert, just an amateur doing his best and trying to help.

I fully realise this is a partially "incomplete" report, and in order to just get on with things, I have decided to move back to Windows, where I have no problems at all. Presently, I have removed my Linux installation and cannot reproducce for further investigation.

It is worth mentioning that a contact, via Unexpected Maker's Discord Server has experienced exactly the same difficulties, especially with the UM Tiny S3 and has himself reverted to using Windows, where the same problem isn't being experienced for him too.

**Comment by UnexpectedMaker** [comment] 2022-04-29 20:54
@me-no-dev I'm able to build and deploy on the Mac with all of my boards, and @prplz is able to build and deploy on Windows with all of my S3 boards, but I had to install latest from Master and manually run `python get.py` . 2.0.3RC1 from boards manager put my TinyS3 into the same boot loop.

So I'm thinking that installing from board manager is not installing the tool chain properly?

**Comment by billsmithem** [comment] 2022-04-30 23:42
I'm seeing the same issue on the TinyS3 running esptool.py v3.3-dev on Ubuntu 20.04.

**Comment by UnexpectedMaker** [comment] 2022-04-30 23:55
> I'm seeing the same issue on the TinyS3 running esptool.py v3.3-dev on Ubuntu 20.04.

3.3-dev is older than 3.3. Can you try upgrading your esptool?

**Comment by billsmithem** [comment] 2022-05-01 11:42
Where might I find 3.3? I just re-did the manual install per https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html and 3.3-dev is the version that was installed again.

**Comment by Jason2866** [comment] 2022-05-01 13:47
There is no valid entry for the ESP32-S3 in this [file](https://github.com/espressif/arduino-esp32/blob/gh-pages/package_esp32_dev_index.json) So updating Arduino with this package_esp32_index.json is a working way.
Not using Arduino IDE. This [file](https://github.com/espressif/arduino-esp32/blob/master/package/package_esp32_index.template.json) is actual and worth a try.
@me-no-dev  The package.json in branch gh-pages should be updated.

**Comment by Idirianuk** [comment] 2022-05-09 19:49
> Is esptool.py v3.3 used? Only the v3.3 includes the needed header patching fix for the S3. Without you encounter issues with boards and partitions using a other scheme than 4MB

Have just rebuilt a Linux Mint 20.03LTS installation and have set up the toolchain using...

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

...in the Additional Boards Manager URL settings and can confirm that the problem is present and can confirm that v3.3 of esptool.py is being used.

Using default settings, the serial monitor is repeatedly showing:

`ESP-ROM:esp32s3-20210327`
`Build:Mar 27 2021`
`rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)`
`Saved PC:0x403bb22e`
`SPIWP:0xee`
`mode:DIO, clock div:1`
`load:0x3fcd0108,len:0x43c`
`load:0x403b6000,len:0xbd0`
`load:0x403ba000,len:0x29c8`
`entry 0x403b61d8`

**Comment by me-no-dev** [comment] 2022-05-11 10:26
> There is no valid entry for the ESP32-S3 in this [file](https://github.com/espressif/arduino-esp32/blob/gh-pages/package_esp32_dev_index.json) So updating Arduino with this package_esp32_index.json is not a working way.

Those are just list of boards. Not something required for S3 to work. In the 2.0.3 final, there is an S3 board too. Testing on x86 linux ix an issue for me currently as I am buried in ARMs around me. I'll see what I can do.

**Comment by LouBerry** [comment] 2022-06-10 10:01
Hi, just had tried to flash tinyS3 without success on linus as well.

**OS:** Manjaro up-to-date
**IDE:** Arduino 1.8.15, esp32 2.03
**Board:** UM TinyS3

Flashing simple or even emtpy arduino .ino files results in endless serial monitor output like:

```
09:21:56.886 -> ESP-ROM:esp32s3-20210327
09:21:56.886 -> Build:Mar 27 2021
09:21:56.886 -> rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
09:21:56.886 -> Saved PC:0x403bb0ce
09:21:56.886 -> SPIWP:0xee
09:21:56.886 -> mode:DIO, clock div:1
09:21:56.886 -> load:0x3fcd0108,len:0x39c
09:21:56.886 -> load:0x403b6000,len:0x9a4
09:21:56.886 -> load:0x403ba000,len:0x2868
09:21:56.886 -> entry 0x403b61c0
```

Board settings as below

![image](https://user-images.githubusercontent.com/20300852/173041347-f1f30575-05c9-4563-a9e4-ee984e7595e1.png)

Any more information needed?

**Comment by LouBerry** [comment] 2022-06-13 18:39
I tried the same board on windows, which I can confirm is working just fine.

Tried the "ESP32-S3 Dev Module" on linux, without success.
Flashing works but it is not possible to replicate the settings from my screenshot, since not all options are present.

**Comment by me-no-dev** [comment] 2022-06-13 22:07
which one is missing? you should have all those options for the dev module

**Comment by LouBerry** [comment] 2022-06-15 19:48
These are the settings for the Dev Module I can see.

![image](https://user-images.githubusercontent.com/20300852/173913725-e5382684-e00f-401e-8adb-5b07f35b565e.png)

**Comment by me-no-dev** [comment] 2022-06-16 07:20
And what is missing from the above, that you can not switch to using that config?

**Comment by VojtechBartoska** [comment] 2022-06-27 11:55
Any updates on this?

**Comment by VojtechBartoska** [comment] 2022-07-15 12:54
As far we are not able to reproduce it, please if you still face this issue, share the steps how to reproduce it. Otherwise this issue will be closed. Thanks in advance!

**Comment by VojtechBartoska** [comment] 2022-07-26 13:43
Closing as expired due to no answer. If it's still needed, please reopen the issue. Thanks for understanding.

**Closed** 2022-07-26 13:43 UTC
Labels: Resolution: Unable to reproduce, Chip: ESP32-S3, Status: Needs investigation
