### ISSUE TITLE
esp32 bluetooth mac scan

### ISSUE THREAD

**Issue by mahdikan** [espressif/arduino-esp32#956] opened 2017-12-30 11:28 UTC
hello everyone
i want to scan for bluetooth devices near the esp32 to find thats mac, but i couldn't find example in arduino
please help me if you have an example.
thanks
mahdi

**Comment by mahdikan** [comment] 2018-01-03 09:48
any body?

**Comment by copercini** [comment] 2018-01-03 12:24
For now there is just a IDF example: https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bt_discovery but you can run it on arduino with small changes

**Comment by mahdikan** [comment] 2018-01-03 12:51
hi copercini 
thanks alot for your mention, but i can't change it to arduino , i copied the code in arduino but there are som errors,
may i asked you to explain changing the code?

**Comment by copercini** [comment] 2018-01-03 13:06
Humm, the BT core of Arduino is a bit outdated in relation to IDF, so for now you can use [arduino as IDF component](https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md) or wait a bit to @me-no-dev update the arduino core with the last IDF version

**Comment by mahdikan** [comment] 2018-01-03 13:13
how long should i wait to update arduino core?

**Comment by beegee-tokyo** [comment] 2018-01-04 08:22
@copercini, the [example](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bt_discovery) will not work, as it requires esp-idf V3.0 at least. At least on PlatformIO we are on esp-idf V2.50200.0

**Comment by beegee-tokyo** [comment] 2018-01-04 09:24
@mahdikan are you searching for Bluetooth devices or for BLE devices?
The [BLE scan](https://github.com/nkolban/ESP32_BLE_Arduino/tree/f8fe9d7cdfb20caa54b70849826d1ac6e375ff78/examples/BLE_scan) example is working.

I have it running on my ESP32, but it finds only BLE devices (of course).

**Comment by mahdikan** [comment] 2018-01-06 05:53
thanks to beegee yes the ble scan is working but i want to scan smartphones and cars bluetooth mac

**Comment by c0ryd** [comment] 2018-01-20 03:40
What are you trying to do with the MAC address?  If you are attempting to identify a specific device (like a presence detector), that’s probably not going to work for you. Many devices have a rolling MAC address, so your sketch might work for ~15 minutes, then break. 
What you might want to go after is the Identity Resolving Key, but as to how to do that I haven’t been able to sort that out just yet.

**Comment by mahdikan** [comment] 2018-01-20 09:30
hello c0ryd 
yes i want to identify  some devices MAC for calculating the repeated costumers in a shop during one month , do you know the rolling MAC address algorithm ? or do you know the way for identify the bluetooth mac?
thanks

**Comment by c0ryd** [comment] 2018-01-20 13:45
I’m far from an expert, but as far as I know the algorithm for the Mac addresses won’t be public, as the whole purpose is for privacy, so your device can’t be tracked like that. 
From what I understand, there is an “identity resolving key” but that’s only available if the device has been paired and bonded with your “sniffer”. 
Perhaps track people instead via WiFi? You would be able to track reconnects easier, and who doesn’t want free WiFi access?  You might even use an iBeacon to push a message to your customers with your WiFi password when they enter the store, to get more people to connect.

**Comment by everslick** [comment] 2018-04-19 10:27
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 10:27 UTC
