### ISSUE TITLE
Abnormal disconnection of HTTPClient

### ISSUE THREAD

**Issue by mytrain** [espressif/arduino-esp32#931] opened 2017-12-17 19:43 UTC
### Hardware:
Board: ESP32 Dev Module
Core Installation/update date: 29/Nov/2017
IDE name: Arduino IDE
SDK Version: v3.0-dev-1325-ge5b2c1cf

### Description:
When opening 2 HTTPClient to 2 different URL, completing the reading of a seconde one witch connection status of both client to 'disconnected'

### Sketch:
[issue931.txt](https://github.com/espressif/arduino-esp32/files/1568518/issue931.txt)

### Outputs:
[D][WiFiGeneric.cpp:265] _eventCallback(): Event: 2 - STA_START
6
6
6
6
[D][WiFiGeneric.cpp:265] _eventCallback(): Event: 4 - STA_CONNECTED
6
6
[D][WiFiGeneric.cpp:265] _eventCallback(): Event: 7 - STA_GOT_IP
[V][HTTPClient.cpp:140] beginInternal(): url: http://www.google.com
[D][HTTPClient.cpp:181] beginInternal(): host: www.google.com port: 80 url: 
[D][HTTPClient.cpp:850] connect():  connected to www.google.com:80
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'HTTP/1.0 404 Not Found'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Type: text/html; charset=UTF-8'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Referrer-Policy: no-referrer'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Length: 1564'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Date: Sun, 17 Dec 2017 19:36:03 GMT'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:968] handleHeaderResponse(): code: 404
[D][HTTPClient.cpp:971] handleHeaderResponse(): size: 1564
[V][HTTPClient.cpp:140] beginInternal(): url: http://www.youtube.com
[D][HTTPClient.cpp:181] beginInternal(): host: www.youtube.com port: 80 url: 
[D][HTTPClient.cpp:850] connect():  connected to www.youtube.com:80
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'HTTP/1.0 404 Not Found'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Type: text/html; charset=UTF-8'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Referrer-Policy: no-referrer'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Content-Length: 1564'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: 'Date: Sun, 17 Dec 2017 19:36:03 GMT'
[V][HTTPClient.cpp:938] handleHeaderResponse(): RX: ''
[D][HTTPClient.cpp:968] handleHeaderResponse(): code: 404
[D][HTTPClient.cpp:971] handleHeaderResponse(): size: 1564
>>>[1] httpFile1[connected] httpFile2[connected] lenFile[1564]]
>>>[2] httpFile1[connected] httpFile2[connected] lenFile[540]]
>>>[3] httpFile1[connected] httpFile2[connected] lenFile[540]]
>>>[2] httpFile1[connected] httpFile2[disconnected] lenFile[0]]
>>>[3] httpFile1[disconnected] httpFile2[disconnected] lenFile[0]]

On last line I do not understand why the httpFile1 instance goes to disconnected.

**Comment by lonerzzz** [comment] 2017-12-19 14:45
@mytrain Can you provide a code sample to let us better help you?

**Comment by mytrain** [comment] 2017-12-19 18:07
Arduino sketch is in attachement issue931.txt (sadly it is not possible to upload an ino extension file on github 👎 )

**Comment by everslick** [comment] 2018-04-19 10:48
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 10:48 UTC
