### ISSUE TITLE
SPIFFS in Platformio

### ISSUE THREAD

**Issue by holema** [espressif/arduino-esp32#670] opened 2017-09-27 06:56 UTC
### Hardware:
Board:							NODE32S
Core Installation/update date:			27.09.2017
IDE name:						Arduino IDE

### Description:
On the ESP6288 in the Platformio IDE it was possible to create a SPIFFS file very easy and upload it to the ESP. I`m able to use the SPIFFS and the FS Library and to store values in a filesystem but I also need to create some files and send them to the ESP. Is there a way to get compile the data-folder?

**Comment by me-no-dev** [comment] 2017-09-27 07:25
it is a bit more complex task on ESP32 and I am thinking/working on it. The issue is that the partition scheme needs to be read and decoded in order for the proper size of the partition to be obtained and used for creating the SPIFFS image.

**Comment by holema** [comment] 2017-09-27 08:57
Thanks for your fast reply. Is there a Milestone for this feature?

**Comment by me-no-dev** [comment] 2017-09-27 09:49
nope, but I will look into it soon ;) I already have a branch that includes the needed mkspiffs in this repo. It's a matter of figuring out the proper way to get the config and add the code to the upload sketch tool.

**Comment by roboticboyer** [comment] 2017-09-30 07:03
@me-no-dev could be used [esp8266fs-plugin](https://github.com/esp8266/arduino-esp8266fs-plugin/releases/download/0.3.0/ESP8266FS-0.3.0.zip) also for ESP32?
This plugin creates the data folder/directory inside the SPIFFS memory

**Comment by me-no-dev** [comment] 2017-09-30 07:17
@roboticboyer please read my answer above :)

**Comment by holema** [comment] 2017-10-16 15:09
Hello me-no-dev,
I saw hat it is now possible to generate a SPIFFS file in the platformIO. But is this also uploaded to the device, or do I need a further step for this?

**Comment by copercini** [comment] 2017-10-16 15:24
@roboticboyer me-no-dev's released a version for ESP32 here: https://github.com/me-no-dev/arduino-esp32fs-plugin

**Comment by me-no-dev** [comment] 2017-10-16 16:40
@holema you should ask the platformio guys about that :) I am not familiar with their tools and procedures

**Comment by holema** [comment] 2017-10-16 19:16
@me-no-dev and @copercini  thanks a lot. 
@me-no-dev : does your asyncwebserver works with the SPIFFS System that is implemented up to now?

**Comment by me-no-dev** [comment] 2017-10-16 19:28
@holema yes

**Comment by everslick** [comment] 2018-04-19 07:06
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 07:06 UTC
