### ISSUE TITLE
RTC_CPU_FREQ_80M was not declared in this scope

### ISSUE THREAD

**Issue by 4ngeliwi** [espressif/arduino-esp32#9739] opened 2024-05-31 16:04 UTC
### Board

TTGO T1

### Device Description

HX711

### Hardware Configuration

ttgo, wx711 and a rs485 but this isnt used

### Version

latest master (checkout manually)

### IDE Name

Arduino IDE

### Operating System

Windows 22

### Flash frequency

not sure

### PSRAM enabled

no

### Upload speed

115200

### Description

Code doesnt run on my pc, i tried running it on other peoples pc and it works, its just mine, i changed versions of the arduino and the libraries but nothing seems to work.

### Sketch

```cpp
rtc_cpu_freq_config_t config;
  rtc_clk_cpu_freq_get_config(&config);
  rtc_clk_cpu_freq_to_config(RTC_CPU_FREQ_80M, &config);
  rtc_clk_cpu_freq_set_config_fast(&config);
  scale.begin(LOADCELL_DOUT_PIN, LOADCELL_SCK_PIN);
  //scale.set_scale(INSERT YOUR CALIBRATION FACTOR);
  scale.set_scale(213.510);
  scale.tare();               // reset the scale to 0
  scale.power_up();
```

### Debug Message

```plain
exit status 1

'RTC_CPU_FREQ_80M' was not declared in this scope; did you mean 'RTC_XTAL_FREQ_40M'?
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment] 2024-06-03 17:34
@lucasssvaz can you please help with triage? I am not sure, if there is potentially some issue. Thanks

**Comment by lucasssvaz** [comment] 2024-10-09 16:07
Duplicate of https://github.com/espressif/arduino-esp32/issues/7616

**Closed by lucasssvaz** 2024-10-09 16:07 UTC
Labels: Status: Awaiting triage, Type: 3rd party Boards
