### ISSUE TITLE
problem with zigbee library

### ISSUE THREAD

**Issue by ruediger218** [espressif/arduino-esp32#9752] opened 2024-06-02 17:44 UTC
### Board

esp32c6

### Device Description

esp32c6 dev module

### Hardware Configuration

no

### Version

v3.0.0

### IDE Name

arduino ide

### Operating System

windows 11

### Flash frequency

80mhz

### PSRAM enabled

yes

### Upload speed

115200

### Description

i want to develop a zigbee device with 4 on/off endpoints + a light endpoint for brightness configuration.
my sourcecode based on the HA_on_off_light example
i am not able to get callbacks when changing brightness. therefor i found a hint in using the function

this works perfect when i compile per commandline.
in arduino ide i get the messages:
'zb_zcl_parsed_hdr_t' was not declared in this scope
undefined reference to `zb_buf_get_tail_func(unsigned char, unsigned int)'
undefined reference to `zb_buf_begin_func(unsigned char)'

### Sketch

```cpp
bool rawCmdHandlerCb(uint8_t bufid) 
{
    uint8_t buf[zb_buf_len(bufid)];
    zb_zcl_parsed_hdr_t *cmd_info = ZB_BUF_GET_PARAM(bufid, zb_zcl_parsed_hdr_t);
    printf("cluster id: 0x%x, command id: %d\n", cmd_info->cluster_id, cmd_info->cmd_id);
    memcpy(buf, zb_buf_begin(bufid), sizeof(buf));
	if ((cmd_info->cluster_id == 8) && (cmd_info->cmd_id == 4)){
		ESP_LOGI("RAW", "brightness: %d", buf[0]);
    pumpendrehzahl = buf[0];
	}
	else{
		ESP_LOGI("RAW", "bufid: %d size: %d", bufid, sizeof(buf));
		for (int i = 0; i < sizeof(buf); ++i) {
			ESP_LOGI("RAW", "buf[%d]: %d", i, buf[i]);
			//printf("0x%02X ", buf[i]);
		}
		//printf("\n");
	}

	//return true;
    return false;
}
```

### Debug Message

```plain
lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld.exe: sketch\BewZigbee03.ino.cpp.o: in function `rawCmdHandlerCb(unsigned char)':
BewZigbee03.ino:238: undefined reference to `zb_buf_len_func(unsigned char)'
riscv32-esp-elf/bin/ld.exe: BewZigbee03.ino:239: undefined reference to `zb_buf_get_tail_func(unsigned char, unsigned int)'
riscv32-esp-elf/bin/ld.exe: BewZigbee03.ino:241: undefined reference to `zb_buf_begin_func(unsigned char)'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by P-R-O-C-H-Y** [comment] 2024-06-02 19:54
@ruediger218 Closing this as duplicate of #9745

**Closed by P-R-O-C-H-Y** 2024-06-02 19:54 UTC
Labels: Status: Awaiting triage
