### ISSUE TITLE
is it support ESP32 board for Arduino newest version 2.1.1 ?why I meet error

### ISSUE THREAD

**Issue by woodgreat** [espressif/arduino-esp32#8403] opened 2023-07-12 03:52 UTC
### Board

ESP32-CAM

### Device Description

ESP32-CAM

### Hardware Configuration

no need connect or yes ,the bug is on also

### Version

v2.0.9

### IDE Name

arduino 2.1.1

### Operating System

windows10

### Flash frequency

40mhz

### PSRAM enabled

no

### Upload speed

11520

### Description

------------------------------------ code
void setup() {

}

void loop() {

}
------------------------------------ output
ϵͳ�Ҳ���ָ����·����

exit status 1

Compilation error: exit status 1
-------------------------------------
why?

### Sketch

```cpp
void setup() {

}

void loop() {

}
```

### Debug Message

```plain
ϵͳ�Ҳ���ָ����·����

exit status 1

Compilation error: exit status 1
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by SuGlider** [comment] 2023-07-12 14:51
@woodgreat - I have just updated my Arduino IDE from 2.1.0 to 2.1.1, keeping the same ESP32 Arduino Core 2.0.9 that was already installed before.

I could compile and upload an empty sketch as well as some other examples.
Please make sure that you select again the ESP32 target board and its related serial port for uploading.

![image](https://github.com/espressif/arduino-esp32/assets/65977697/61ed47b0-ddb4-48c7-9fc8-7622e1a26eff)

**Comment by woodgreat** [comment] 2023-07-14 03:10
OK,I will try more than once

**Comment by woodgreat** [comment] 2023-07-14 03:11
maybe I use Offline ESP32 library, Is that cause the problem?where is your lib came from?

**Comment by lbernstone** [comment] 2023-07-14 05:31
Stable release version is 2.0.9
https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html

**Comment by wz12378** [comment] 2023-07-21 13:36
arduino ide 2.1.1 ,Versionv2.0.9.My situation is the same as yours,how can I solve it.help

**Comment by SuGlider** [comment] 2023-07-21 19:30
@wz12378 - What is exactly the problem?

**Comment by wz12378** [comment] 2023-07-23 08:38
> - 问题到底是什么？

like this：
ϵͳ�Ҳ���ָ����·����

exit status 1

Compilation error: exit status 1

**Comment by SuGlider** [comment] 2023-07-24 11:55
If the problem is that the Console Ouput seems weird with  `ϵͳ�Ҳ���ָ����·����` Serial Console output, please make sure that it has been changed to 115200 instead of usual 9600 default baud rate.

**Comment by RayC012** [comment] 2023-07-27 10:21
did you put your file under some folders that consist of prohibited character like" $%&"

**Comment by VojtechBartoska** [comment] 2023-08-21 14:27
this is supposed to work, can we close this issue @woodgreat?

**Closed** 2023-09-04 12:20 UTC
Labels: Resolution: Unable to reproduce, Resolution: Awaiting response, IDE: Arduino IDE
