### ISSUE TITLE
HardwareSerial.setTimeout() invalid when serial pin connected to TTL to RS232 converter

### ISSUE THREAD

**Issue by techzzx** [espressif/arduino-esp32#774] opened 2017-10-25 10:10 UTC
### Hardware:
Board:	ESP32 Devkitc (ESP32_Core_board_V2)
Core Installation/update date:	25/10/2017
IDE name:	Arduino IDE 1.8.1
Flash Frequency:	80Mhz
Upload Speed:	921600

### Description:
The HardwareSerial.setTimeout() function seem not work properly when pin 16 17 connect to UART to RS232 converter or even not connected to anything. 
Did I missed something or did something wrong ? Or it is the limitation of ESP32 ?
Does anyone face the same situation? I haven't figure out how to solve this problem yet.

### Sketch:
```cpp
HardwareSerial mySerial(2);  // UART1/Serial1 pins 16,17
char targetString[] = "OK";
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println(F("Start..."));
  mySerial.begin(9600);
  mySerial.setTimeout(20000); // receive target string in 20s
}

void loop() {
  // put your main code here, to run repeatedly:
  Serial.println(F("Working..."));
  while (false == mySerial.find(targetString)) {
    Serial.println("Not receive.");
  }
}
```

### Debug Messages:
```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:11904
entry 0x40078a3c
Start...
Working...
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.
Not receive.

```
There are many "Not receive" msg log out per second.

**Comment by everslick** [comment] 2018-04-19 07:25
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 07:25 UTC
