### ISSUE TITLE
Wemos lolin32 lite doesn't work

### ISSUE THREAD

**Issue by appie2002** [espressif/arduino-esp32#1002] opened 2018-01-15 18:46 UTC
### Hardware:
Board:							wemos lolin32 lite
Core Installation/update date:			15/january/2018
IDE name:							Arduino IDE
flash Frequency:				40Mhz
Upload Speed:						921600

### Description:
if i select wemos lolin32 from boards, and i run a random script, it gives an error. I tried selecting multiple boards f.e. ESP32 Dev module but I think the problem is that wemos lolin32 lite is not yet compatible.

### Sketch:
```cpp

#include <Arduino.h>

void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}
```

### Debug Messages:
Arduino: 1.8.5 (Linux), Board: "WEMOS LOLIN32, 80MHz, 921600"

/home/pi/Downloads/arduino-1.8.5/arduino-builder -dump-prefs -logger=machine -hardware /home/pi/Downloads/arduino-1.8.5/hardware -hardware /home/pi/Arduino/hardware -tools /home/pi/Downloads/arduino-1.8.5/tools-builder -tools /home/pi/Downloads/arduino-1.8.5/hardware/tools/avr -built-in-libraries /home/pi/Downloads/arduino-1.8.5/libraries -libraries /home/pi/Arduino/libraries -fqbn=espressif:esp32:lolin32:FlashFreq=80,UploadSpeed=921600 -ide-version=10805 -build-path /tmp/arduino_build_179735 -warnings=none -build-cache /tmp/arduino_cache_468112 -prefs=build.warn_data_percentage=75 -verbose /home/pi/Downloads/arduino-1.8.5/examples/01.Basics/Blink/Blink.ino
/home/pi/Downloads/arduino-1.8.5/arduino-builder -compile -logger=machine -hardware /home/pi/Downloads/arduino-1.8.5/hardware -hardware /home/pi/Arduino/hardware -tools /home/pi/Downloads/arduino-1.8.5/tools-builder -tools /home/pi/Downloads/arduino-1.8.5/hardware/tools/avr -built-in-libraries /home/pi/Downloads/arduino-1.8.5/libraries -libraries /home/pi/Arduino/libraries -fqbn=espressif:esp32:lolin32:FlashFreq=80,UploadSpeed=921600 -ide-version=10805 -build-path /tmp/arduino_build_179735 -warnings=none -build-cache /tmp/arduino_cache_468112 -prefs=build.warn_data_percentage=75 -verbose /home/pi/Downloads/arduino-1.8.5/examples/01.Basics/Blink/Blink.ino
Using board 'lolin32' from platform in folder: /home/pi/Arduino/hardware/espressif/esp32
Using core 'esp32' from platform in folder: /home/pi/Arduino/hardware/espressif/esp32
Detecting libraries used...
"/home/pi/Arduino/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM -DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h" -DHAVE_CONFIG_H "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/config" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/bluedroid" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/app_trace" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/app_update" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/bootloader_support" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/bt" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/driver" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/esp32" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/esp_adc_cal" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/ethernet" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/fatfs" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/freertos" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/heap" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/jsmn" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/log" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/mdns" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/mbedtls" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/mbedtls_port" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/newlib" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/nvs_flash" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/openssl" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/spi_flash" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/sdmmc" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/spiffs" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/tcpip_adapter" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/ulp" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/vfs" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/wear_levelling" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/xtensa-debug-module" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/console" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/soc" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/newlib" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/coap" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/wpa_supplicant" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/expat" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/json" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/nghttp" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/lwip" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti  -c -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10805 -DARDUINO_LOLIN32 -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD="LOLIN32"  -DESP32 -DCORE_DEBUG_LEVEL=0 "-I/home/pi/Arduino/hardware/espressif/esp32/cores/esp32" "-I/home/pi/Arduino/hardware/espressif/esp32/variants/lolin32" "/tmp/arduino_build_179735/sketch/Blink.ino.cpp" -o "/dev/null"
Generating function prototypes...
"/home/pi/Arduino/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM -DMBEDTLS_CONFIG_FILE="mbedtls/esp_config.h" -DHAVE_CONFIG_H "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/config" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/bluedroid" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/app_trace" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/app_update" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/bootloader_support" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/bt" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/driver" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/esp32" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/esp_adc_cal" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/ethernet" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/fatfs" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/freertos" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/heap" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/jsmn" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/log" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/mdns" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/mbedtls" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/mbedtls_port" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/newlib" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/nvs_flash" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/openssl" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/spi_flash" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/sdmmc" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/spiffs" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/tcpip_adapter" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/ulp" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/vfs" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/wear_levelling" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/xtensa-debug-module" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/console" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/soc" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/newlib" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/coap" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/wpa_supplicant" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/expat" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/json" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/nghttp" "-I/home/pi/Arduino/hardware/espressif/esp32/tools/sdk/include/lwip" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti  -c -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10805 -DARDUINO_LOLIN32 -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD="LOLIN32"  -DESP32 -DCORE_DEBUG_LEVEL=0 "-I/home/pi/Arduino/hardware/espressif/esp32/cores/esp32" "-I/home/pi/Arduino/hardware/espressif/esp32/variants/lolin32" "/tmp/arduino_build_179735/sketch/Blink.ino.cpp" -o "/tmp/arduino_build_179735/preproc/ctags_target_for_gcc_minus_e.cpp"
fork/exec /home/pi/Arduino/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++: no such file or directory
Error compiling for board WEMOS LOLIN32.
```

**Comment by MarkyAD** [comment] 2018-01-15 21:49
The problem is that you dont have a compiler, from the next to last line...

fork/exec /home/pi/Arduino/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++: no such file or directory

Looks like you're running this on ARM, there is no esp32 toolchain for ARM (yet).

**Comment by appie2002** [comment] 2018-01-16 17:06
thank you!
do you maybe know another core or driver that supports the wemos lolin32 lite that I can use?

**Comment by MarkyAD** [comment] 2018-01-16 21:56
As far as esp32 on arm, then not currently. Probably just a matter of time until someone cross-compiles the toolchain for pi, so I wouldn't be surprised to see that change eventually. In the meantime, esp8266 does have an arm toolchain, and they're just a couple dollars.

**Comment by beegee-tokyo** [comment] 2018-01-17 01:55
@appie2002 check out [Using Raspberry Pi as a development environment](https://esp32.com/viewtopic.php?t=256) maybe that solution still works.

**Comment by MarkyAD** [comment] 2018-01-17 04:07
@beegee-tokyo maybe still works with older esp32 core versions (I didnt try yet) but with current git version it barfs on various assert macro expansions when it gets to compiling core code.

**Comment by MarkyAD** [comment] 2018-01-17 06:29
Tried on esp-idf as well with no better luck, it nags about compiler version not supported, compiles some stuff successfully, then dies on compile of bootloader. Figured I'd at least give a try at compiling toolchain-ng but my debian jessie install is stale as several package versions were too old. Blah. I'll try again if I get a chance to recompile them, it would be nice to get the arm toolchain working.

**Comment by AgreeDK** [comment] 2018-01-17 16:40
There is different version of the LOLIN32 Lite board, I have 2 different version and only the one with lolin32 on the pcb is working.

**Comment by AgreeDK** [comment] 2018-01-17 16:55
The boards without Lolin32 on the PCB, work for me now, try change the upload from 921600 to 115200

**Comment by MarkyAD** [comment] 2018-01-17 21:40
@beegee-tokyo Thanks for the pointer to the information on that site. I was able to compile a working arm toolchain. I distributed the compile among 16 raspberry pi cores and it completed in around 2 hours.

@appie2002 if you are still interested in compiling esp32 code on that pi, I can get you a copy of the arm toolchain or explain how I did it.

**Comment by everslick** [comment] 2018-04-19 10:51
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 10:51 UTC
