### ISSUE TITLE
Global EEPROM instance always returns 0

### ISSUE THREAD

**Issue by ArchGryphon9362** [espressif/arduino-esp32#6067] opened 2021-12-26 15:43 UTC
### Board

ESP32 Dev Module

### Device Description

N/A

### Hardware Configuration

N/A

### Version

v2.0.1

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

N/A

### PSRAM enabled

no

### Upload speed

115200

#### Expected Behaviour
After running EEPROM.begin(2048) on the global EEPROM instance, EEPROM.length() should return 2048

#### Current Behaviour
After running EEPROM.begin(2048) on the global EEPROM instance, EEPROM.length() returns 0

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment] 2022-04-11 11:37
Hello, can you please retest this on v2.0.3-rc1?

**Comment by ArchGryphon9362** [comment] 2022-04-11 18:14
I am not currently sure where my second test ESP is, so can't it test at the moment. When I find it I will try it out

**Comment by VojtechBartoska** [comment] 2022-05-04 19:33
Any news on this?

**Comment by ArchGryphon9362** [comment] 2022-05-04 21:02
Oh shit sorry, I couldn't find my ESP so I didn't end up testing. Sorry...

**Comment by UnicodeMan** [comment] 2022-05-06 17:34
Hi. I tested this today with platformIO, pressed update all (updating both libraries and boards, but the result is still that EEPROM returns 0 when used outside in other classes and such. In other words, behaviour is still not global.

**Comment by lbernstone** [comment] 2022-05-06 17:58
@UnicodeMan Are you testing the result of EEPROM.begin()?  If it fails to initialize (perhaps your nvs partition is full), then length will still be 0.  Setting the EEPROM length is one of the last things done in the begin function.

**Comment by UnicodeMan** [comment] 2022-05-07 07:16
I tested the result. EEPROM.begin(4096) returns 1

**Comment by UnicodeMan** [comment] 2022-05-07 15:57
Seeing as EEPROM is deprecated on ESP32, I decided to use Preferences library. It works great. So anyone having issues with EEPROM should consider migrating to Preferences (though I see why EEPROM is still used).

**Comment by ArchGryphon9362** [comment] 2022-05-07 16:02
Interesting. The reason I'm using it is because I tried to port over a project for the ESP8266 and got it working, but nothing would persist a restart. I just added lots of Serial.print statements to find what the culprit was in the saving code and it came down to this. Seeing as it wasn't any sort of dynamic number, I hardcoded the expected length, but a fix to the EEPROM library would be useful nonetheless.

**Comment by ArchGryphon9362** [comment] 2022-05-07 16:03
> Seeing as EEPROM is deprecated on ESP32, I decided to use Preferences library. It works great. So anyone having issues with EEPROM should consider migrating to Preferences (though I see why EEPROM is still used).

Interesting. The reason I'm using it is because I tried to port over a project for the ESP8266 and got it working, but nothing would persist a restart. I just added lots of Serial.print statements to find what the culprit was in the saving code and it came down to this. Seeing as it wasn't any sort of dynamic number, I hardcoded the expected length, but a fix to the EEPROM library would be useful nonetheless.

**Comment by UnicodeMan** [comment] 2022-05-07 16:07
Nevermind

> Seeing as EEPROM is deprecated on ESP32, I decided to use Preferences library. It works great. So anyone having issues with EEPROM should consider migrating to Preferences (though I see why EEPROM is still used).
Nevermind. Same issues in this library aswell.

**Comment by lbernstone** [comment] 2022-05-07 17:06
Checking the nvs status is more difficult than just erasing it.  Open a command prompt and find esptool (usually %userdata%/Arduino15/packages/esp32/tools/esptool/<version>) and run `esptool erase_flash`.  That will wipe you whole device, and then you can upload your firmware again.  If that fixes Preferences, then please test EEPROM again.

**Comment by UnicodeMan** [comment] 2022-05-07 17:16
> Checking the nvs status is more difficult than just erasing it. Open a command prompt and find esptool (usually %userdata%/Arduino15/packages/esp32/tools/esptool/) and run `esptool erase_flash`. That will wipe you whole device, and then you can upload your firmware again. If that fixes Preferences, then please test EEPROM again.

did that. behaviour didn't change. Both Preferences and EEPROM libraries don't do what they ought to.

**Comment by lbernstone** [comment] 2022-05-07 18:07
Does the [StartCounter](https://github.com/espressif/arduino-esp32/blob/master/libraries/Preferences/examples/StartCounter/StartCounter.ino) example work?

**Comment by UnicodeMan** [comment] 2022-05-07 18:13
> Does the [StartCounter](https://github.com/espressif/arduino-esp32/blob/master/libraries/Preferences/examples/StartCounter/StartCounter.ino) example work? Please make sure you have debugging set to verbose to check for any errors.

Works fine. Currently at counter value 14 and going up.

**Comment by lbernstone** [comment] 2022-05-07 19:24
build_flags = -DCORE_DEBUG_LEVEL=5

**Comment by UnicodeMan** [comment] 2022-05-08 08:10
example library prints this:
`...`
`ets Jun  8 2016 00:22:57`
` `
`rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)`
`configsip: 0, SPIWP:0xee`
`clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00`
`mode:DIO, clock div:2`
`load:0x3fff0030,len:1184`
`load:0x40078000,len:12776`
`load:0x40080400,len:3032`
`entry 0x400805e4`
`[␀␘␂␂␂��m␑um����2-hal-cpu.c:211] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz`
` `
`Current counter value: 68`
`Restarting in 10 seconds...`
`...`

Interestingly, with the flags, my project now has problems, when:
[ESP32-bluetooth-ArduinoBased.zip](https://github.com/espressif/arduino-esp32/files/8646571/ESP32-bluetooth-ArduinoBased.zip)

1) I create Preferences object in main.cpp,
2) I pass the object to my library class. Within the library class the Preferences object is defined as a pointer
3) I try to use Preferences as before (with . replaced as ->, in the library, of course)
The following will cause reboot loop.

`...`
`Rebooting...
`ets Jun  8 2016 00:22:57
` `
`rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)`
`configsip: 0, SPIWP:0xee`
`clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00`
`mode:DIO, clock div:2`
`load:0x3fff0030,len:1184`
`load:0x40078000,len:12776`
`load:0x40080400,len:3032`
`entry 0x400805e4`
`Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.`
` `
`Core  0 register dump:`
`PC      : 0x400d318a  PS      : 0x00060130  A0      : 0x800d187b  A1      : 0x3ffe3b90  `
`A2      : 0x00000000  A3      : 0x3f400175  A4      : 0x00000000  A5      : 0x00000000 ` 
`A6      : 0x3ffbae98  A7      : 0x00000000  A8      : 0x8008a0d8  A9      : 0x3ffe3b70  `
`A10     : 0x00000000  A11     : 0x00000064  A12     : 0x00000000  A13     : 0x00060123  `
`A14     : 0x00060120  A15     : 0x00000001  SAR     : 0x00000018  EXCCAUSE: 0x0000001c  `
`EXCVADDR: 0x00000004  LBEG    : 0x4008657d  LEND    : 0x4008658d  LCOUNT  : 0xffffffff  `


`Backtrace:0x400d3187:0x3ffe3b900x400d1878:0x3ffe3bb0 0x400d22ea:0x3ffe3bd0 0x400d275c:0x3ffe3bf0 0x400ddbff:0x3ffe3c10 0x400827d1:0x3ffe3c40 0x400791f2:0x3ffe3c90  |<-CORRUPTED `

ELF file SHA256: 0000000000000000
` `
`Core  0 register dump:`
`PC      : 0x400d318a  PS      : 0x00060130  A0      : 0x800d187b  A1      : 0x3ffe3b90  `
`A2      : 0x00000000  A3      : 0x3f400175  A4      : 0x00000000  A5      : 0x00000000  `
`A6      : 0x3ffbae98  A7      : 0x00000000  A8      : 0x8008a0d8  A9      : 0x3ffe3b70  `
`A10     : 0x00000000  A11     : 0x00000064  A12     : 0x00000000  A13     : 0x00060123  `
`A14     : 0x00060120  A15     : 0x00000001 `
`...`
`--- exit ---`
`(i CTRL-C-ed the serial output)`

I am attaching whole project that can be opened as-is in VSCode / VSCode-based applications.
My noob thinking is that there are problems with global variables in some kind library that is causing undefined behaviour.
I license the project with MIT license. 
I will try to reproduce the error with way less bloated and less complex project. It should throw same errors when adding preferences abject in seperate library (that is class-based). If it doesn't fail, throwing in LCD_I2C library and using LCD at the same time might be a good idea (good as in making the ESP fail).

**Comment by UnicodeMan** [comment] 2022-05-08 09:36
Dismiss previously sent project file, it had a possible problem because Preferences object was used before it was passed on.

**Comment by UnicodeMan** [comment] 2022-05-08 09:57
Dismiss previously sent project file, it had a problem because Preferences object was used before it was passed on.
Making it less complex by using the Preferences library in the class only (creating the object in the class). It magically has no problem now. Why? No idea. No global use, I guess.
[ESP32-bluetooth-ArduinoBased.zip](https://github.com/espressif/arduino-esp32/files/8646757/ESP32-bluetooth-ArduinoBased.zip)

**Comment by VojtechBartoska** [comment] 2022-05-26 09:19
Can I consider this as solved?

**Comment by UnicodeMan** [comment] 2022-05-28 11:26
I think it is better left as open. 
Even though EEPROM is deprecated, it's functionality is seriously damaged by the fact it has problems when its used globally. It's still not solved, just stalled.

**Comment by lbernstone** [comment] 2022-06-14 18:54
see #6572

**Comment by mrengineer7777** [comment] 2023-05-21 06:06
Likely fixed by PR https://github.com/espressif/arduino-esp32/pull/6910.

**Closed by mrengineer7777** 2023-05-21 06:06 UTC
Labels: Resolution: Awaiting response, Status: Needs investigation
