### ISSUE TITLE
Can't read input data form pins if use WiFi

### ISSUE THREAD

**Issue by stas0** [espressif/arduino-esp32#975] opened 2018-01-07 19:02 UTC
Hi!

I one pin for read temperature from several ds18b20 sensors and one pin for read data from analog input.

All errors starting after I started use WiFi connection. Before using WiFi I used G22 and G4 pins and all works great. After I started use  WiFi(WiFi.begin(ssid, password)), none of pins not working. 
I found that this link https://github.com/espressif/arduino-esp32/issues/825
Its says that if I use WiFi I need 

> use pins 32 and above when WiFi is ON

Why???
What about rest pins???
Ok. For test I use G34 and G35 pins. Analog pin works great. but pin for temperature not woking. 
I aloso added cli() and sei() between reading sensors data, but it also not working.

Whats wrong?

**Comment by stickbreaker** [comment] 2018-01-07 19:19
@stas0 
`cli()` and `sei()` have no effect on the ESP32. I have modified the `OneWire.h` library to be compatible with the ESP32 here: [esp32 OneWire.h](https://github.com/stickbreaker/OneWire) 

Try it. 

Don't know about your Analog input problems.

Chuck.

**Comment by stas0** [comment] 2018-01-07 19:27
@stickbreaker 
http://prntscr.com/hxb53s
Very nice, nice!
At screen you can see that all works great! I used previous version and got some strange effect. Because I use only one pin for several sensors old version return wrong data. Current version working great.

**Comment by stas0** [comment] 2018-01-07 19:30
It takes years of testing the board, it's still very raw.

**Comment by everslick** [comment] 2018-04-19 11:16
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 11:16 UTC
