### ISSUE TITLE
ESP32 Deep sleep API

### ISSUE THREAD

**Issue by savagerex** [espressif/arduino-esp32#8361] opened 2023-06-28 01:19 UTC
### Board

ESP32 S3

### Device Description

Sensor -  IIS3dwb
External Flash

### Hardware Configuration

None

### Version

v2.0.8

### IDE Name

Arduino IDE

### Operating System

Windows 10

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

I have two sample codes.

two codes use "esp_deep_sleep_start();"  API.

but two codes have different power consumption.

the problem is when codes use "esp_deep_sleep_start();" API, but power consumption is different.

below is more power consumption code.

### Sketch

```cpp
#include "SPI.h"
#include <SerialFlash.h>
#include "IIS3DWB.h"
#include "Sensor.h"
#include "WifiTask.h"
#include "BleTask.h"
#include "SensorPreferences.h"
#include <ESP32Time.h>
#include <WiFi.h>
#include <MQTT.h>
#include "LedBlinker.h"
#include "BoardConfig.h"

ESP32Time rtc;

#define EnableWifi 1
#define EnableBle 1
#define Enable_LedTask  1

int WirelessMode = OFF_MODE;
int RtcYear =0;

extern int SetRtcFlag;
extern int SetMqttServerFlag;

int SetMeasureMode = 0;

unsigned long BleStartTime;
unsigned long BleEndTime;
unsigned long AbsBleTime;

unsigned long WifiStartTime;
unsigned long WifiEndTime;
unsigned long AbsWifiTime;

int BleConnect = 0;
int BleDisConnect = 1;

int TaskMeasureFlag = 0;




//const char *topic = "DataTopic";
const char *topic1a = "1a/report";
const char *topic2a = "2a/report";
const char *topic3a = "3a/report";
const char *topic4a = "4a/report";
const char *topic5a = "5a/report";

WiFiClient net;
MQTTClient client(41000);

SPIClass SPI2(HSPI);

#define CSPIN    10

uint8_t Ascale = AFS_8G;

float aRes;                              // scale resolutions per LSB for the accel
float accelBias[3] = {0.0f, 0.0f, 0.0f}; // offset biases for the accel
int16_t IIS3DWBData[4] = {0};            // Stores the 16-bit signed sensor output
uint8_t IIS3DWBRawData[6] = {0};            // Stores the 16-bit signed sensor output
int16_t destination[3];
float ax, ay, az, accelTemp;             // variables to hold latest accel data values
uint8_t IIS3DWBstatus;
//long values[40];
uint8_t ui8txLogBuf[20];
uint32_t i, j, k, m, n, o;
uint32_t IsrK;
int DryFlag = 1;
int FileWriteFlag = 0;
int FileReadFlag = 0;
int packet_counter = 1;

unsigned long StartTime;
unsigned long EndTime;

volatile bool DataReady = false;

#define PACKAGE 600
#define TotalData  14850    //4k : 6*4000/120=200 //27k : 6*27000/120=1350  //6*27000*11/120 =14850   //6*27000*11        //3*27,000*11  3*26,000*11    //44000    4445*11
#define ReadTotalData  44  //4k : 6*4000/12000=2 //27k : 6*27000/18000 = 9  //6*27000*11 / 18000 = 99 // 297000 //297  //6*27000*11 / 162000 = 22

uint8_t DataBufWrite[125];
uint8_t DataBufRead[41000];

IIS3DWB IIS3DWB(CSPIN);

unsigned long StartTestTime;
unsigned long EndTestTime;

unsigned long StartWriteTime;
unsigned long EndWriteTime;

#define uS_TO_S_FACTOR 1000000  /* Conversion factor for micro seconds to seconds */
#define TIME_TO_SLEEP  30
RTC_DATA_ATTR int bootCount = 0;


#define detect_pin   21

#define sensorPin 4
//int sensorPin = 4;    
int sensorValue = 0;

int SensorOneValue = 0;
int SensorTwoValue = 0;
int SensorThreeValue = 0;
int SensorFourValue = 0;
int SensorFiveValue = 0;
int SensorAvrValue = 0;

int SensorOneAfterValue = 0;
int SensorTwoAfterValue = 0;
int SensorThreeAfterValue = 0;
int SensorFourAfterValue = 0;
int SensorFiveAfterValue = 0;
int SensorAvrAfterValue = 0;

int SensorOneAfterValue1 = 0;
int SensorTwoAfterValue1 = 0;
int SensorThreeAfterValue1 = 0;
int SensorFourAfterValue1 = 0;
int SensorFiveAfterValue1 = 0;
int SensorAvrAfterValue1 = 0;




unsigned long RecordStartTime;
unsigned long RecordEndTime;
unsigned long AbsRecordTime;

xQueueHandle xQueue;

SerialFlashFile flashFile;

void IRAM_ATTR IntOneIsr() {
     //DryFlag = 1;    
       DataReady = true;  
     
}

void connect() {
  Serial.print("checking wifi...");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(1000);
  }

  Serial.print("\nconnecting...");

  while (!client.connect("arduino", "public", "public")) {
    Serial.print(".");
    delay(1000);
  }

  Serial.println("\nconnected!");

  
}




void wakeup_reason() {
  esp_sleep_wakeup_cause_t wakeup_reason;

  wakeup_reason = esp_sleep_get_wakeup_cause();
  switch (wakeup_reason)
  {
    case ESP_SLEEP_WAKEUP_EXT0 : Serial.println("Wakeup caused by external signal using RTC_IO"); break;
    case ESP_SLEEP_WAKEUP_EXT1 : Serial.println("Wakeup caused by external signal using RTC_CNTL"); break;
    case ESP_SLEEP_WAKEUP_TIMER : Serial.println("Wakeup caused by timer"); break;
    case ESP_SLEEP_WAKEUP_TOUCHPAD : Serial.println("Wakeup caused by touchpad"); break;
    case ESP_SLEEP_WAKEUP_ULP : Serial.println("Wakeup caused by ULP program"); break;
    default :
      Serial.printf("Wakeup was not caused by deep sleep: %d\n", wakeup_reason);
      rtc.setTime(30, 24, 15, 17, 1, 2021);  // 17th Jan 2021 15:24:30
      //rtc.setTime(1609459200);  // 1st Jan 2021 00:00:00
      //rtc.offset = 7200; // change offset value

      break;
  }
}





void DumpStatistics() {
  Serial.printf("[Psram] Free:%i, Size:%i, MinFree:%i, MaxAlloc:%i\n", ESP.getFreePsram(),ESP.getPsramSize(), ESP.getMinFreePsram(), ESP.getMaxAllocPsram());
  Serial.printf("[Heap] Free:%i, Size:%i, MinFree:%i, MaxAlloc:%i\n", ESP.getFreeHeap(), ESP.getHeapSize(), ESP.getMinFreeHeap(), ESP.getMaxAllocHeap());
  Serial.printf("[Stack] TaskGetStackHighWaterMark: %i\n", uxTaskGetStackHighWaterMark(NULL));
}

void PrintTaskCreateError(BaseType_t xReturned) {
  switch(xReturned) {
    case errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY:
      Serial.println(F("errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY"));
      break;
    case errQUEUE_BLOCKED:
      Serial.println("errQUEUE_BLOCKED");
      break;
    case errQUEUE_YIELD:
      Serial.println("errQUEUE_YIELD");
      break;
    default:
      Serial.printf("Unknown Error: %d\n", xReturned);
      break;
  }
}

void WifiTask(void *pvParameters) {
  (void) pvParameters;
  Serial.printf("WifiTask running on core %i\n", xPortGetCoreID());

  for (;;) {
      WifiTask();
      delay(10);
  } 
  vTaskDelete( NULL );
}

void BleTask(void *pvParameters) {
  (void) pvParameters;
  Serial.printf("BleTask running on core %i\n", xPortGetCoreID());

  for (;;) {
      BleUartTaskStep();
      delay(10);
  } 
  vTaskDelete( NULL );
}

//void IRAM_ATTR BtnIsr() {
//     SetMeasureMode = 1;
//     BleStartTime = millis();
//     led_off();
//}


void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);

  wakeup_reason();
 
  esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);

  
  pinMode(detect_pin, INPUT);


  pinMode(led1GPin, OUTPUT);
  pinMode(led1RPin, OUTPUT);
  pinMode(led2GPin, OUTPUT);
  pinMode(led2RPin, OUTPUT);
  pinMode(led3GPin, OUTPUT);
  pinMode(led3RPin, OUTPUT);
  pinMode(led4GPin, OUTPUT);
  pinMode(led4RPin, OUTPUT);


            digitalWrite(led1GPin, HIGH);
            digitalWrite(led1RPin, HIGH);
            digitalWrite(led2GPin, HIGH);
            digitalWrite(led2RPin, HIGH);
            digitalWrite(led3GPin, HIGH);
            digitalWrite(led3RPin, HIGH);
            digitalWrite(led4GPin, HIGH);
            digitalWrite(led4RPin, HIGH);



  pinMode(ButtonPin, INPUT);
  pinMode(SensorPowerPin, OUTPUT);
  digitalWrite(SensorPowerPin, HIGH);
  delay(15);


  SensorOneValue = analogRead(sensorPin);
  SensorTwoValue = analogRead(sensorPin);
  SensorThreeValue = analogRead(sensorPin);
  SensorFourValue = analogRead(sensorPin);
  SensorFiveValue = analogRead(sensorPin);

  SensorAvrValue = (SensorThreeValue + SensorFourValue + SensorFiveValue)/3;

  //client.publish(topic2, String(bootCount));
  //client.publish(topic2, String(SensorAvrValue));

  //attachInterrupt(ButtonPin, BtnIsr, RISING);

  esp_sleep_enable_ext0_wakeup(GPIO_NUM_18, 0);   //SR Board :0, EVB2 Board :1

  pinMode(CSPIN, OUTPUT);
      digitalWrite(CSPIN, HIGH);

      Serial.println("IIS3DWB accel...");
      uint8_t c = IIS3DWB.getChipID();  // Read CHIP_ID register for IIS3DWB
      Serial.print("IIS3DWB "); Serial.print("I AM "); Serial.print(c, HEX); Serial.print(" I should be "); Serial.println(0x7B, HEX);
      Serial.println(" ");

      if (c == 0x7B) // check if all SPI sensors have acknowledged
      {
        Serial.println("IIS3DWB is online...");
        Serial.println(" ");

        // reset IIS3DWB to start fresh
        IIS3DWB.reset();

        // get accel sensor resolution, only need to do this once
        aRes = IIS3DWB.getAres(Ascale);
        Serial.print("aRes = ");
        Serial.println(String(aRes));

//        IIS3DWB.selfTest();

        IIS3DWB.init(Ascale); // configure IIS3DWB

//        IIS3DWB.offsetBias(accelBias);
        Serial.println("accel biases (mg)"); Serial.println(1000.0f * accelBias[0]); Serial.println(1000.0f * accelBias[1]); Serial.println(1000.0f * accelBias[2]);
        Serial.println(" ");
        delay(1000);


      }
      else
      {
        if (c != 0x6A) Serial.println(" IIS3DWB not functioning!");
        while (1) {};
      }
      delay(100);
      attachInterrupt(INTONE, IntOneIsr, RISING);
      esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);

      xQueue = xQueueCreate(1200, sizeof(IIS3DWBRawData));
  
  Preferences preferences;
  preferences.begin(PrefNamespace, false); 
  String ssidPrim = preferences.getString(PrefSsidPrim,"");
  RtcYear = preferences.getInt(PrefYear);
  String mqttServer = preferences.getString(PrefMqttServer,"");
  preferences.end();

  Serial.println("Hello");
  Serial.println(ssidPrim);
  Serial.println(RtcYear);
  Serial.println(mqttServer);

  BleStart();
  
  if (ssidPrim != "") {
    WirelessMode = WIFI_MODE;
    Serial.println("WIFI MODE");
    WifiStartTime = millis();
  } else {
    WirelessMode = OFF_MODE;
    Serial.println("OFF MODE");
  }  
  
  BaseType_t xReturned = NULL;

  if (Enable_LedTask) {
    xReturned = xTaskCreatePinnedToCore(
                  LedBuzzerTask
                  , "LedAndBuzzerTask"   // A name just for humans
                  //, 2*1024 // This stack size can be checked & adjusted by reading the Stack Highwater,
                  , Ram_LedBuzzerTask // This stack size can be checked & adjusted by reading the Stack Highwater,
                  , NULL
                  , 2  // Priority, with 3 (configMAX_PRIORITIES - 1) being the highest, and 0 being the lowest.
                  , NULL
                  , 1);
    if ( xReturned != pdPASS ) {
      Serial.println("LedAndBuzzerTask create error.");
      PrintTaskCreateError(xReturned);
      DumpStatistics();
    } else {
      Serial.println("LedAndBuzzerTask create success.");
    }
  }
  
  if (EnableWifi) {
    xReturned = xTaskCreatePinnedToCore(
                    WifiTask
                    , "WifiTask"   // A name just for humans
                    //, 1024*5  // This stack size can be checked & adjusted by reading the Stack Highwater,
                    , Ram_WifiTask  // This stack size can be checked & adjusted by reading the Stack Highwater,
                    , NULL
                    , 2  // Priority, with 3 (configMAX_PRIORITIES - 1) being the highest, and 0 being the lowest.
                    , NULL
                    , ARDUINO_RUNNING_CORE);
    if ( xReturned != pdPASS ) {
    SF_PRINTLN("[Error] WifiTask create error.");
      PrintTaskCreateError(xReturned);
      DumpStatistics();
      } else {
        SF_PRINTLN("WifiTask create success.");
      }
  }

  if (EnableBle) {
    xReturned = xTaskCreatePinnedToCore(
                    BleTask
                    , "BleTask"   // A name just for humans
                    //, 1024*5  // This stack size can be checked & adjusted by reading the Stack Highwater,
                    , Ram_WifiTask  // This stack size can be checked & adjusted by reading the Stack Highwater,
                    , NULL
                    , 2  // Priority, with 3 (configMAX_PRIORITIES - 1) being the highest, and 0 being the lowest.
                    , NULL
                    , ARDUINO_RUNNING_CORE);
    if ( xReturned != pdPASS ) {
    SF_PRINTLN("[Error] BleTask create error.");
      PrintTaskCreateError(xReturned);
      DumpStatistics();
      } else {
        SF_PRINTLN("BleTask create success.");
      }
  }


   if (RtcYear != 0)
   {
       Serial.println(rtc.getDateTime());
       delay(1000);
   }
   else if (RtcYear == 0)
   {
      while(SetRtcFlag == 0)
      {
        Serial.println("please enter Date and Time");
        delay(1000);
      }
   }

  if ( WiFi.status() != WL_CONNECTED) {
      while(WiFi.status() != WL_CONNECTED)
      {
        Serial.println("please connect Wifi");
        delay(1000);
      }
  }
 
  if (WiFi.status() == WL_CONNECTED) { 
      if (mqttServer != "") {
         SetMqttServerFlag = 1;
      } else {
          while(SetMqttServerFlag == 0)
          {
            Serial.println("please enter MQTT Sevrer IP");
            delay(1000);
          }
      }
  }

    SPI2.begin(SCK, MISO, MOSI, FCSPIN);
    //SPI2.begin(SCK, MISO, MOSI);
    SPI2.setDataMode(SPI_MODE0);
    SPI2.setBitOrder(MSBFIRST);
    SPI2.setFrequency(SPI_FREQUENCY);

    if (!SerialFlash.begin(SPI2 , FCSPIN)) {
    while (1) {
      Serial.println(F("Unable to access SPI Flash chip"));
      delay(1000);
       }
     }
      //We start by formatting the flash...
      uint8_t id[5];
      SerialFlash.readID(id);
      Serial.printf("ID: %02X %02X %02X\n", id[0], id[1], id[2]);
      delay(500);
//      SerialFlash.eraseAll();
    
//      delay(1000);
      Serial.println("Flash Ready");

 bootCount++;


//      while (!SerialFlash.ready()) {
//        delay(500);
//        digitalWrite(led1GPin, HIGH);
//        delay(500);
//        digitalWrite(led1GPin, LOW);
//      }

      xTaskCreatePinnedToCore(taskOne, "TaskOne", 4096, NULL, 2, NULL, 0);
      xTaskCreatePinnedToCore(taskTwo, "TaskTwo", 4096, NULL, 2, NULL, 1);

}

void taskOne( void * parameter ) {
   disableCore0WDT();

//   SerialFlash.create("123.txt", 1782500);   // 6*27000*11 = 1782000    //858000=3*26000*11      891000=3*27000*11
//   flashFile = SerialFlash.open("123.txt");
//
//   if (!flashFile) {
//     Serial.println("There was an error opening the file for writing");
//     return;
//   }
   
   for (;;) {
//        SerialFlash.create("123.txt", 1782500);   // 6*27000*11 = 1782000    //858000=3*26000*11      891000=3*27000*11
//        flashFile = SerialFlash.open("123.txt");
//      
//        if (!flashFile) {
//          Serial.println("There was an error opening the file for writing");
//          return;
//        }

        //while(1)
        //{
        //delayMicroseconds(1);
        
        if (DataReady) {
           DataReady = false;
           if (n == 0) {
            StartTestTime = millis();
           }
           
          //IIS3DWB.readAccelData(IIS3DWBData);
          IIS3DWB.readAccelRawData(IIS3DWBRawData);
    
          n++; 
          m++;

          xQueueSend(xQueue, &IIS3DWBRawData, portMAX_DELAY);
    
//          for(i = 0; i < 6; i++) {
//              DataBufWrite[k] = IIS3DWBRawData[i];
//              //DataBufWrite[j] = values[i];
//              //file.write(DataBufWrite[j]);
//              //j+=1;
//              k+=1;
//          }
//         
//          if(k==120)
//          {
//            if (m == 0) {
//              StartWriteTime = millis();
//            }
//            flashFile.write(DataBufWrite, 120); 
//            k=0; 
//            m+=1; 
//            j+=1;
//          }

          //flashFile.write(IIS3DWBRawData, 6);
          //j+=1;
//          if(m==225)
//          {
//                EndWriteTime = millis();
//                Serial.print("**************Write Time*************");
//                Serial.println(EndWriteTime - StartWriteTime);
//                m=0;
//          }
          
    
//          if(j == TotalData) {
//             flashFile.close();
//             //FileReadFlag = 1;
//             j=0;
//    
//             while (1) {
//                delay(1000);
//                digitalWrite(led1GPin, HIGH);
//                delay(1000);
//                digitalWrite(led1GPin, LOW);
//              }
//             
//          }
            
            if(m == 297000)
            {
              Serial.println("11 Sec Data");


//      client.publish(topic2a, String(bootCount));
//      client.publish(topic3a, String(SensorAvrValue));
      SensorOneAfterValue1 = analogRead(sensorPin);
      SensorTwoAfterValue1 = analogRead(sensorPin);
      SensorThreeAfterValue1 = analogRead(sensorPin);
      SensorFourAfterValue1 = analogRead(sensorPin);
      SensorFiveAfterValue1 = analogRead(sensorPin);
      SensorAvrAfterValue1 = (SensorThreeAfterValue1 + SensorFourAfterValue1 + SensorFiveAfterValue1)/3;
      client.publish(topic5a, String(SensorAvrAfterValue1));


              
              while (1) {
                delay(1000);
                digitalWrite(led1GPin, HIGH);
                delay(1000);
                digitalWrite(led1GPin, LOW);
              }
            }
    
            if (n == 26667) {     
                EndTestTime = millis();
                Serial.print("**************SPI Sensor Time*************");
                Serial.println(EndTestTime - StartTestTime);
                n = 0;
            }
          
         }
       //}
       
   }
   vTaskDelete( NULL );
}

void taskTwo( void * parameter ) {
   disableCore1WDT();
   uint8_t xQueueData[6] = {0};

   SerialFlash.create("123.txt", 1782500);   // 6*27000*11 = 1782000    //858000=3*26000*11      891000=3*27000*11
   flashFile = SerialFlash.open("123.txt");
   if (!flashFile) {
     Serial.println("There was an error opening the file for writing");
     SerialFlash.eraseAll();
     delay(100);
     return;
   }
   
   for (;;) {
          xQueueReceive(xQueue, (void *)&xQueueData, portMAX_DELAY);

          for(i = 0; i < 6; i++) {
              DataBufWrite[k] = xQueueData[i];

//              if (i==1)
//              {
//                DataBufWrite[k] = xQueueData[i] >>1;
//              }
//              else
//              {
//                DataBufWrite[k] = xQueueData[i];
//              }
              
              //DataBufWrite[j] = values[i];
              //file.write(DataBufWrite[j]);
              //j+=1;
              k+=1;
          }
         
          if(k==120)
          {
//            if (m == 0) {
//              StartWriteTime = millis();
//            }
            flashFile.write(DataBufWrite, 120); 
            k=0; 
            //m+=1; 
            j+=1;
          }

          if(j == TotalData) {
             flashFile.close();
             FileReadFlag = 1;
             j=0;
          }
    
//        delay(1000);
//        digitalWrite(led2GPin, HIGH);
//        delay(1000);
//        digitalWrite(led2GPin, LOW);
//
        if (FileReadFlag == 1) {
            FileReadFlag = 0;
            //SerialFlashFile flashFile;
            RecordStartTime = millis();
            flashFile = SerialFlash.open("123.txt");
            for(i=0; i< ReadTotalData; i++)
            {
                //memset(DataBufRead,0,9);
                flashFile.read(DataBufRead, 40500); //18000  //6000  


                
                client.loop();
                //delay(1);  
              
                if (!client.connected()) {
                  connect();
                }

//                destination[0] = (int16_t)((int16_t)DataBufRead[1] << 8)  | DataBufRead[0] ;  
//                destination[1] = (int16_t)((int16_t)DataBufRead[3] << 8)  | DataBufRead[2] ;
//                destination[2] = (int16_t)((int16_t)DataBufRead[5] << 8)  | DataBufRead[4] ;
//
//                ax = (float)destination[0]*aRes;
//                ay = (float)destination[1]*aRes;   
//                az = (float)destination[2]*aRes;
//
//                ax=ax*1000;
//                ay=ay*1000;
//                az=az*1000;
//
//                String ThreeAxisData = " x = " + String(ax) + " y = " + String(ay) + " z = " + String(az);
//                client.publish(topic, String(ThreeAxisData));
//                delay(20);

              RecordEndTime = millis();
              AbsRecordTime = RecordEndTime - RecordStartTime;
              if (AbsRecordTime >= 600000)
              {
                  Serial.println("Going to sleep now : 60 Sec Timeout");
                  delay(1000);
                  esp_deep_sleep_start();
              }
                
               
               //char *DataBuf = (char*)ui8txLogBuf;
               char *DataBuf = (char*)DataBufRead;
               //client.publish(topic, DataBuf, PACKAGE+2, false, 0);
               bool PubData = client.publish(topic1a, DataBuf, 40500, false, 0);  //18000 //6000
               //Serial.println(PubData);
               
            }
            Serial.println("MQTT Finish");
            delay(100); 
            

      SensorOneAfterValue = analogRead(sensorPin);
      SensorTwoAfterValue = analogRead(sensorPin);
      SensorThreeAfterValue = analogRead(sensorPin);
      SensorFourAfterValue = analogRead(sensorPin);
      SensorFiveAfterValue = analogRead(sensorPin);
      SensorAvrAfterValue = (SensorThreeAfterValue + SensorFourAfterValue + SensorFiveAfterValue)/3;
      client.publish(topic2a, String(bootCount));
      client.publish(topic3a, String(SensorAvrValue));     
      client.publish(topic4a, String(SensorAvrAfterValue));


            flashFile.close();
            delay(100);                                                 //Add
            SerialFlash.remove("123.txt");
            delay(100);                                                 //Add
             while (1) {
//                delay(1000);
//                digitalWrite(led2GPin, HIGH);
//                delay(1000);
//                digitalWrite(led2GPin, LOW);
//                delay(1000);
                Serial.println("Going to sleep now");
                delay(100);
                esp_deep_sleep_start();

               
              }
            
        }
   }
   vTaskDelete( NULL );
}

void loop() {
  // put your main code here, to run repeatedly:
  if(SetRtcFlag == 1)
  {
     SetRtcFlag = 0;
 
     Preferences preferences;
     preferences.begin(PrefNamespace, false);
     int RtcYear = preferences.getInt(PrefYear);
     int RtcMonth = preferences.getInt(PrefMonth);
     int RtcDay = preferences.getInt(PrefDay);
     int RtcHour = preferences.getInt(PrefHour);
     int RtcMinute = preferences.getInt(PrefMinute);
     int RtcSecond = preferences.getInt(PrefSecond);
     preferences.end();

     rtc.setTime(RtcSecond, RtcMinute, RtcHour, RtcDay, RtcMonth, RtcYear);
  }

  if (SetMqttServerFlag == 1) {
      SetMqttServerFlag = 0;
      //MqttServerStart();

      Preferences preferences;
      preferences.begin(PrefNamespace, false); 
      String mqttServer = preferences.getString(PrefMqttServer,"");
      preferences.end();
     
     client.begin(mqttServer.c_str(), net);

     Serial.print("\nconnecting...");
     while (!client.connect("arduino", "public", "public")) {
        Serial.print(".");
        delay(1000);
     }
    
     Serial.println("\nconnected!");


      
//      SensorOneAfterValue = analogRead(sensorPin);
//      SensorTwoAfterValue = analogRead(sensorPin);
//      SensorThreeAfterValue = analogRead(sensorPin);
//      SensorFourAfterValue = analogRead(sensorPin);
//      SensorFiveAfterValue = analogRead(sensorPin);
//      SensorAvrAfterValue = (SensorThreeAfterValue + SensorFourAfterValue + SensorFiveAfterValue)/3;
//      client.publish(topic3, String(SensorAvrAfterValue));

      
  }

//  if (BleDisConnect == 1)
//  {
//    //BleConnect = 0;
//    BleEndTime = millis();
//    AbsBleTime = BleEndTime - BleStartTime;
//    if (AbsBleTime >= 60000)
//    {
//        Serial.println("Enter Measure Mode");
//        delay(1000);
//        SetMeasureMode = 0;
//    }
//  }
//
//  if (BleConnect == 1)
//  {
//    //BleDisConnect = 0;
//    BleStartTime = millis();
//  }
//  
//  if (SetMeasureMode == 0)
//  {
//     if(WiFi.status() == WL_CONNECTED)
//     {
//           led_slow_blink();
//           Serial.println("Enter Test");
//           IIS3DWBData[3] = IIS3DWB.readTempData(); // get IIS3DWB chip temperature
//           accelTemp = ((float) IIS3DWBData[3]) / 256.0f + 25.0f;
//           Serial.println(accelTemp);
//
//           String DataBuf = rtc.getDateTime() + "-" + (String)accelTemp;
//           client.publish(topic, DataBuf);
//           delay(1000);
//     }
//      
//  }

//  sensorValue = analogRead(sensorPin);

//  if(sensorValue <= 1701) {
//  Serial.println(sensorValue);
//  led_red_slow_blink();             
//  }

  client.loop();
  //client.publish(topic, "Hello world");
  //Serial.println(rtc.getDateTime());
  delay(1000);



}
```

### Debug Message

```plain
NONE
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by lbernstone** [comment] 2023-06-28 03:14
There are different power domains which can be shut down during deep sleep.  The automatic method will shut down unused domains, so if you use a method that allows you turn off RTC peripherals (eg timer or ext1), you will draw less current during sleep.
https://docs.espressif.com/projects/esp-idf/en/v4.4.5/esp32/api-reference/system/sleep_modes.html#power-down-of-rtc-peripherals-and-memories

**Comment by savagerex** [comment] 2023-06-28 07:26
Got it, Thanks!!!

**Comment by savagerex** [comment] 2023-06-29 01:16
when i use timer & ext1 at same time.  power consumption is higher.

about this part, does your team can modify ??

because our product need  "timer & ext1" to wake up ESP32

**Comment by SuGlider** [comment] 2023-06-29 10:57
From the documentation: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/system/sleep_modes.html#configuring-ios-deep-sleep-only

The circuit may also influence in the results. 

![image](https://github.com/espressif/arduino-esp32/assets/65977697/00f850c6-e342-402e-a620-482455fd46ba)

**Comment by SuGlider** [comment] 2023-06-29 11:04
@savagerex - I have done an experiment with using the Osciloscope. I have used an ESP32-S3-Mini Devkit + ESP-PROG + GPIO18 connected to 3.3v. A simplified sketch to just deep sleeep for 3 seconds and stay waked up for another 3 seconds.

I could not see any change in the current. When I comment out the line that sets GPIO18 to wakeup `esp_sleep_enable_ext0_wakeup(GPIO_NUM_18, 0)`, it also produces the exactly same current graph.

This is the OSciloscope Screenshot. Waked up = about 35mA and Deep Sleep = about 1mA.

![image](https://github.com/espressif/arduino-esp32/assets/65977697/0cfc695b-acd9-4a9d-9524-4198b289935a)


This is the Sketch used to test it:

``` cpp
#define uS_TO_S_FACTOR 1000000  /* Conversion factor for micro seconds to seconds */
#define TIME_TO_SLEEP  3

void wakeup_reason() {
  esp_sleep_wakeup_cause_t wakeup_reason;

  wakeup_reason = esp_sleep_get_wakeup_cause();
  switch (wakeup_reason)
  {
    case ESP_SLEEP_WAKEUP_EXT0 : Serial.println("Wakeup caused by external signal using RTC_IO"); break;
    case ESP_SLEEP_WAKEUP_EXT1 : Serial.println("Wakeup caused by external signal using RTC_CNTL"); break;
    case ESP_SLEEP_WAKEUP_TIMER : Serial.println("Wakeup caused by timer"); break;
    case ESP_SLEEP_WAKEUP_TOUCHPAD : Serial.println("Wakeup caused by touchpad"); break;
    case ESP_SLEEP_WAKEUP_ULP : Serial.println("Wakeup caused by ULP program"); break;
    default :
      Serial.printf("Wakeup was not caused by deep sleep: %d\n", wakeup_reason);
      break;
  }
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);

  wakeup_reason();

  esp_sleep_enable_timer_wakeup(TIME_TO_SLEEP * uS_TO_S_FACTOR);
  esp_sleep_enable_ext0_wakeup(GPIO_NUM_18, 0);   //SR Board :0, EVB2 Board :1
  Serial.printf("\n\r=======\n\rhold %d sec ON\n\r=============\n\r", TIME_TO_SLEEP);
  delay(TIME_TO_SLEEP * 1000);
  Serial.printf("=====>> Going to sleep now : %d Sec Timeout\n\r", TIME_TO_SLEEP);

  esp_deep_sleep_start();

}

void loop() {}

```

**Comment by SuGlider** [comment] 2023-06-29 12:22
@savagerex  - Please try it executing `rtc_gpio_isolate(GPIO_NUM_18);`  in `setup()` before going into deep sleep.

**Comment by savagerex** [comment] 2023-06-30 01:40
I add rtc_gpio_isolate(GPIO_NUM_18);
the power consumption is 1mA.
we hope the power consumption is 6~7uA.

**Comment by SuGlider** [comment] 2023-06-30 08:33
Espressif technical customer support team from China has run a test with deep_sleep example in esp-idf to only module. hardware ESP32-S3-MINI-1-N8 and esp-idf version esp-idf v4.4.4 

Three Test cases: 
1) timer and ext0 wakeup source 
2) only timer 
3) only ext0 

The current in all three test cases is 8 μA.

The sketch posted to this issue uses the same IDF calls that we used in our testing.

We believe that there is something  in the current circuit design that causes the different current consumption.

**Comment by SuGlider** [comment] 2023-06-30 08:40
I also run an Arduino example with the 3 cases (both Timer + EXT0, just Timer and just EXT0). I used the S3 mini Devkit, therefore its circuit consumed more current than just the module.

The current consumption was exactly the same in all three cases.

I also can't see.any difference.
Therefore, we can't reproduce this issue.

It shall be something related to the circuit design and functionality.

**Comment by VojtechBartoska** [comment] 2023-08-18 13:08
Closing as answered.

**Closed by VojtechBartoska** 2023-08-18 13:08 UTC
Labels: Area: ESP-IDF related, Type: Question, Chip: ESP32-S3
