### ISSUE TITLE
I passed (vscode +IDF) AddThe arduino component, but there was an error compiling it

### ISSUE THREAD

**Issue by hzhh110** [espressif/arduino-esp32#8253] opened 2023-05-26 07:57 UTC
### Related area

V:4.4.4

### Hardware specification

ESP32-S3

### Is your feature request related to a problem?

![Snip20230526_2](https://github.com/espressif/arduino-esp32/assets/19906209/5faf8e06-c12e-4ed1-873d-7348ab719b18)

### Describe the solution you'd like

I passed (vscode +IDF) AddThe arduino component, but there was an error compiling it

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by tom-borcin** [comment] 2023-05-26 11:52
Closing the issue as a duplicate of #8254 originally opened in ESP-IDF repo.

**Closed by tom-borcin** 2023-05-26 11:52 UTC
Labels: Type: Feature request
