### ISSUE TITLE
Support of unsigned long long in WString

### ISSUE THREAD

**Issue by JacekDob** [espressif/arduino-esp32#1066] opened 2018-02-02 12:31 UTC
### Hardware:
IDE name:							Arduino IDE
### Description:
Please add support of unsigned long long in WString

**Comment by helmar74** [comment] 2018-03-16 15:20
Added WString.cpp and WString.h ton sonoff directory, got following compile error:

Arduino: 1.8.5 (Windows 10), Board: "ESP32 Dev Module, DOUT, 80MHz, 4MB (32Mb), 115200, None"

WString.cpp:1: error: 'String' does not name a type

 String::String(unsigned long long value, unsigned char base)



Anything I can try?

**Comment by juanimoni** [comment] 2018-03-17 22:53
Hi JacekDob, like helmar74, I got a compiler error too. 
........\Tasmota\webserver.ino: In function 'void HandleInformation()':

webserver:1934: error: call of overloaded 'String(uint64_t)' is ambiguous

   func += F("}1" D_ESP_CHIP_ID "}2"); func += String(ESP.getChipId());

any advice ?                                                                     ^

**Comment by JacekDob** [comment] 2018-03-18 13:37
To compile tasmota esp32 you need to edit and add in arudino-esp32 files:

In [your_dir]\Arduino\hardware\espressif\esp32\cores\esp32\WString.cpp:
```
String::String(unsigned long long value, unsigned char base)
{
    init();
    char buf[1 + 8 * sizeof(unsigned long long)];
    ultoa(value, buf, base);
    *this = buf;
}
```

In [your_dir]\Arduino\hardware\espressif\esp32\cores\esp32\WString.h:
```
explicit String(unsigned long long, unsigned char base = 10);
```

**Comment by helmar74** [comment] 2018-03-18 15:01
yeah! That fixed it, thank's a lot!

**Comment by helmar74** [comment] 2018-03-18 15:07
Next issue ;-)
I compiled it and send it to a ESP32 it's starting, but the ESP didn't connect to Accesspoint. 
The conifguration in user_config.h is fine, as I'm using the same for other tasmota projects.
Here's output of serial log:
0:00:00 APP: Baudrate eingestellt auf 115200

00:00:00 Projekt sonoffESP32 Sonoff (Topic sonoff, Fallback DVES_00000000, GroupTopic sonoffs) Version 5.12.0c-STAGED
00:00:00 WIF: verbinden mit AP1  in Modus 11
00:00:15 WIF: Verbindung fehlgeschlagen da der AP nicht antwortet (timeout)
00:00:15 WIF: verbinden mit AP1  in Modus 1

I also changed GroupTopic in user_config.h. it's ignored somehow

**Comment by helmar74** [comment] 2018-03-18 15:40
[https://github.com/espressif/arduino-esp32/issues/1234](url)

**Comment by everslick** [comment] 2018-04-19 12:14
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 12:14 UTC
