### ISSUE TITLE
Extend SD card select timeout

### ISSUE THREAD

**Issue by NomAnor** [espressif/arduino-esp32#6107] opened 2022-01-07 15:32 UTC
### Board

DOIT ESP32 DEVKIT V1

### Device Description

I'm using a common Arduino SD Card PCB that is connected with 14cm wires to the ESP32

### Hardware Configuration

I'm using the VSPI Pins 18, 19, 23 and 5

### Version

other

### IDE Name

Arduino IDE

### Operating System

Arch Linux

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

Updating to arduino-esp32 v2.0.2 caused the SD-Card to not work anymore (previously I used 1.0.6). The solutions in the other issues didn't work.

Reverting all changes in the file sd_diskio.cpp gave me the same functionality as in 1.0.6. 

Looking at the code I suspected the sdWait timeout in the [sdSelectCard](https://github.com/espressif/arduino-esp32/blob/caef4006af491130136b219c1205bdcf8f08bf2b/libraries/SD/src/sd_diskio.cpp#L124) function, because in 1.0.6 a timeout was just ignored but this is now fixed. In other places ([sdWriteBytes](https://github.com/espressif/arduino-esp32/blob/caef4006af491130136b219c1205bdcf8f08bf2b/libraries/SD/src/sd_diskio.cpp#L229)) a timeout of 500ms is used so I changed the value to that and now my card is recognized.

For me just chaning the timeout in v2.0.2 fixed the issue.

### Sketch

Example SD_Test sketch

### Debug Message

Before changing the timeout:
```plain
[   313][W][sd_diskio.cpp:104] sdWait(): Wait Failed
[   313][E][sd_diskio.cpp:126] sdSelectCard(): Select Failed
[   313][W][sd_diskio.cpp:510] ff_sd_initialize(): GO_IDLE_STATE failed
[   318][E][sd_diskio.cpp:795] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
[   627][W][sd_diskio.cpp:104] sdWait(): Wait Failed
[   627][E][sd_diskio.cpp:126] sdSelectCard(): Select Failed
Card Mount Failed
```
After changing the timeout:
```
[    14][W][sd_diskio.cpp:186] sdCommand(): token error [59] 0x5
SD Card Type: SDSC
SD Card Size: 1947MB
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by VojtechBartoska** [comment] 2022-01-07 16:50
Hello, it's  a duplicate of #6081 and will be closed by merging #6103

**Comment by P-R-O-C-H-Y** [comment] 2022-01-20 12:24
@NomAnor Hi, changing timeout to 500ms solves the mounting issue for you? :) Thanks

**Comment by NomAnor** [comment] 2022-01-20 14:13
Sadly not. At first it worked but after a re-upload I had the same problem again. In the end I reverted all changes to `sd_diskio.cpp` back to 1.0.6. I still got the "Select failed" message but because the return was missing in

https://github.com/espressif/arduino-esp32/blob/caef4006af491130136b219c1205bdcf8f08bf2b/libraries/SD/src/sd_diskio.cpp#L125-L129

that was ignored. The missing return is clearly a bug but ignoring the failure kept the code going and I could read files. My SD-Card was rather old maybe it has to do with that.

**Closed** 2022-01-31 11:01 UTC
Labels: Status: In Progress
