### ISSUE TITLE
Non-blocking ADC functions gone

### ISSUE THREAD

**Issue by Triangulix** [espressif/arduino-esp32#5205] opened 2021-05-22 23:21 UTC
Hi

I just updated from 1.0.4 to 1.0.6 and realized that the non-blocking ADC functions adcStart, adcBusy and adcEnd have been removed.

How should we now use the ADC without blocking the program flow while the ADC is working?

**Comment by Triangulix** [comment] 2021-07-23 22:49
I am now stuck on version 1.0.4, the last version with non-broken non-blocking ADC. Great.

**Comment by Triangulix** [comment] 2021-09-22 10:20
Any news on this topic?

**Comment by VojtechBartoska** [comment] 2022-04-07 11:38
Hello @Triangulix , are you able to test your issue on development version [2.0.3-RC1](https://github.com/espressif/arduino-esp32/releases/tag/2.0.3-RC1) to check if this is still valid? ADC was refactored lately.

Take a look on [Docs](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) where is explained how to choose development release version in Arduino IDE.

**Comment by Triangulix** [comment] 2022-04-07 12:02
@VojtechBartoska Since no-one replied for so long I changed the design and the ADCs are not used anymore.

**Comment by sumitmamoria** [comment] 2022-11-18 12:09
@VojtechBartoska I can confirm that the issue is there in the latest version as well.

**Comment by VojtechBartoska** [comment] 2022-11-21 12:42
@sumitmamoria Can you please provide a sketch for reproducing the issue? Thanks!

**Comment by positron96** [comment] 2023-02-14 18:14
The functions are still gone and they would really be useful to me.

@VojtechBartoska the issue is with missing functionality and functions, I don't think a reproducing sketch is possible. You can follow the history here: https://github.com/espressif/arduino-esp32/issues/220

**Comment by VojtechBartoska** [comment] 2023-02-15 15:43
@P-R-O-C-H-Y Can you please triage this request? Thanks!

**Comment by lbernstone** [comment] 2023-07-26 17:20
ADC was refactored to allow the functions to work on all variants (which have different registers for these peripherals).  If you still want this functionality on an esp32, you can add the functions directly to your code [from 1.0.4](https://github.com/espressif/arduino-esp32/blob/1.0.4/cores/esp32/esp32-hal-adc.c#L159-L217)

**Comment by P-R-O-C-H-Y** [comment] 2023-08-16 11:29
If there is anyone who is already trying the new development version 3.0 using IDF-5.1 which is under `esp-idf-v5.1-libs` branch, you can give a try to the new ADC Continuous mode in PR #8490. Any feedback would be welcome. Thanks

**Comment by VojtechBartoska** [comment] 2023-12-21 13:22
Closing this as solved by above mentioned PR.

**Closed by VojtechBartoska** 2023-12-21 13:22 UTC
Labels: Area: Peripherals API, Status: Review needed
