### ISSUE TITLE
SimpleBLE Connection Failed: gatt status 133

### ISSUE THREAD

**Issue by zombodotcom** [espressif/arduino-esp32#995] opened 2018-01-13 21:55 UTC
Board: HiLetgo ESP-WROOM-32 ESP32 ESP-32S

Arduino IDE:

- board: Node32s
flash frequency 80mhz

I keep trying to connect through my android O pixel XL and I get Connection Failed: gatt status 133

Using the SimpleBLE.ino example

**Comment by everslick** [comment] 2018-04-19 10:53
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 10:53 UTC
