### ISSUE TITLE
touch Interrupt and Pin Interrupt are not working together

### ISSUE THREAD

**Issue by skateone** [espressif/arduino-esp32#499] opened 2017-07-10 15:27 UTC
i have a use case where i need to trigger interrupts on pin change and utilise touch at the same time... looks like the combination of the two together are throwing exceptions.

any suggestions?

**Comment by everslick** [comment] 2018-04-19 06:55
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 06:55 UTC
