### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MassimilianoMontagni98** [espressif/arduino-esp32#6433] opened 2022-03-15 16:31 UTC
### Board

esp32doit-devkit-v1

### Device Description

Plain module (ESP32 WROOM 32D) on PCB

### Hardware Configuration

GPIO 16 & 17 Serial2
SPI SD card

### Version

v2.0.2

### IDE Name

PlatformIO

### Operating System

macOS 12.2.1

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

1500000

### Description

When I call `Decompressor::decompress` from `AnotherClass::createDecompressor` I gonna lose something about 6k of stack and I can't understand why. The strange thing is that happening only on the first time that I call `decompress` and at the begging of the function (have a look where the `log_e` are)

What could be the cause of the memory leak? 

### Sketch

```cpp
static void AnotherClass::createDecompressor()
{
    log_e("stack %u", uxTaskGetStackHighWaterMark(NULL));
    auto decompressed = Decompressor::decompress(chunkBytes.data(), chunksLength[currentLengthIndex]);
    try
    {
        SDManager::appendToFile(firmwareFile, decompressed.data, decompressed.len);
    }
    catch (const exception &e)
    {
        log_e("%s", e.what());
    }
}

Decompressor::DecompressResult Decompressor::decompress(uint8_t *buffer, size_t len)
{
    log_e("stack %u", uxTaskGetStackHighWaterMark(NULL));
    tinfl_decompressor inflator = tinfl_decompressor{};
    tinfl_init(&inflator);
    log_e("stack %u", uxTaskGetStackHighWaterMark(NULL));
    DecompressResult result;

    static uint8_t out_buf[65536];
    memset(out_buf, 0, 65536);
    uint8_t *pointer;
    pointer = &out_buf[0];
}
```

### Debug Message

```plain
[E][DriveFirmwareFilename.hpp:84] createDecompressor(): stack 11260
[E][Decompress.cpp:6] decompress(): stack 5316
[E][Decompress.cpp:9] decompress(): stack 4156
[E][DriveFirmwareFilename.hpp:84] createDecompressor(): stack 4156
[E][Decompress.cpp:6] decompress(): stack 4156
[E][Decompress.cpp:9] decompress(): stack 4156
[E][DriveFirmwareFilename.hpp:84] createDecompressor(): stack 4156
[E][Decompress.cpp:6] decompress(): stack 4156
[E][Decompress.cpp:9] decompress(): stack 4156
[E][DriveFirmwareFilename.hpp:84] createDecompressor(): stack 4156
[E][Decompress.cpp:6] decompress(): stack 4156
[E][Decompress.cpp:9] decompress(): stack 4156
[E][DriveFirmwareFilename.hpp:84] createDecompressor(): stack 4156
[E][Decompress.cpp:6] decompress(): stack 4156
[E][Decompress.cpp:9] decompress(): stack 4156
[E][DriveFirmwareFilename.hpp:84] createDecompressor(): stack 4156
[E][Decompress.cpp:6] decompress(): stack 4156
[E][Decompress.cpp:9] decompress(): stack 4156
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment] 2022-03-15 18:03
Your sketch is woefully incomplete.  Unable to reproduce or even understand what your code is doing.  What is DecompressResult?  How is it returned?  What's with `static uint8_t out_buf[65536];`?

**Comment by VojtechBartoska** [comment] 2022-03-29 12:34
Hello @MassimilianoMontagni98, as mentioned above, we need more info. I'm closing this issue due to that. If you are able to provide more info, please do so and reopen this issue. Thanks for your contribtuion.

**Closed by VojtechBartoska** 2022-03-29 12:34 UTC
Labels: Resolution: Awaiting response
