### ISSUE TITLE
esptools/get.exe Downloads "riscv32-esp-elf" Instead of "xtensa-esp-elf" During Manual Install

### ISSUE THREAD

**Issue by Legohead259** [espressif/arduino-esp32#6494] opened 2022-03-28 16:26 UTC
### Board

ESP32-S2 WROOM

### Device Description

ESP32-S2 WROOM on custom PCB

### Hardware Configuration

N/A

### Version

latest master

### IDE Name

VS Code with Arduino Plugin

### Operating System

Windows 10

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

During manual installation of the ESP-Arduino master branch, the "get.exe" command downloads and extracts "riscv-esp-elf". The expected behavior is to download "xtensa-esp-elf" and build esptool appropriately. This results in the IDE not being able to compile ESP code properly.

### Sketch

```cpp
/*
 * Connect the SD card to the following pins:
 *
 * SD Card | ESP32
 *    D2       -
 *    D3       SS
 *    CMD      MOSI
 *    VSS      GND
 *    VDD      3.3V
 *    CLK      SCK
 *    VSS      GND
 *    D0       MISO
 *    D1       -
 */
#include "FS.h"
#include "SD.h"
#include "SPI.h"

void listDir(fs::FS &fs, const char * dirname, uint8_t levels){
    Serial.printf("Listing directory: %s\n", dirname);

    File root = fs.open(dirname);
    if(!root){
        Serial.println("Failed to open directory");
        return;
    }
    if(!root.isDirectory()){
        Serial.println("Not a directory");
        return;
    }

    File file = root.openNextFile();
    while(file){
        if(file.isDirectory()){
            Serial.print("  DIR : ");
            Serial.println(file.name());
            if(levels){
                listDir(fs, file.path(), levels -1);
            }
        } else {
            Serial.print("  FILE: ");
            Serial.print(file.name());
            Serial.print("  SIZE: ");
            Serial.println(file.size());
        }
        file = root.openNextFile();
    }
}

void createDir(fs::FS &fs, const char * path){
    Serial.printf("Creating Dir: %s\n", path);
    if(fs.mkdir(path)){
        Serial.println("Dir created");
    } else {
        Serial.println("mkdir failed");
    }
}

void removeDir(fs::FS &fs, const char * path){
    Serial.printf("Removing Dir: %s\n", path);
    if(fs.rmdir(path)){
        Serial.println("Dir removed");
    } else {
        Serial.println("rmdir failed");
    }
}

void readFile(fs::FS &fs, const char * path){
    Serial.printf("Reading file: %s\n", path);

    File file = fs.open(path);
    if(!file){
        Serial.println("Failed to open file for reading");
        return;
    }

    Serial.print("Read from file: ");
    while(file.available()){
        Serial.write(file.read());
    }
    file.close();
}

void writeFile(fs::FS &fs, const char * path, const char * message){
    Serial.printf("Writing file: %s\n", path);

    File file = fs.open(path, FILE_WRITE);
    if(!file){
        Serial.println("Failed to open file for writing");
        return;
    }
    if(file.print(message)){
        Serial.println("File written");
    } else {
        Serial.println("Write failed");
    }
    file.close();
}

void appendFile(fs::FS &fs, const char * path, const char * message){
    Serial.printf("Appending to file: %s\n", path);

    File file = fs.open(path, FILE_APPEND);
    if(!file){
        Serial.println("Failed to open file for appending");
        return;
    }
    if(file.print(message)){
        Serial.println("Message appended");
    } else {
        Serial.println("Append failed");
    }
    file.close();
}

void renameFile(fs::FS &fs, const char * path1, const char * path2){
    Serial.printf("Renaming file %s to %s\n", path1, path2);
    if (fs.rename(path1, path2)) {
        Serial.println("File renamed");
    } else {
        Serial.println("Rename failed");
    }
}

void deleteFile(fs::FS &fs, const char * path){
    Serial.printf("Deleting file: %s\n", path);
    if(fs.remove(path)){
        Serial.println("File deleted");
    } else {
        Serial.println("Delete failed");
    }
}

void testFileIO(fs::FS &fs, const char * path){
    File file = fs.open(path);
    static uint8_t buf[512];
    size_t len = 0;
    uint32_t start = millis();
    uint32_t end = start;
    if(file){
        len = file.size();
        size_t flen = len;
        start = millis();
        while(len){
            size_t toRead = len;
            if(toRead > 512){
                toRead = 512;
            }
            file.read(buf, toRead);
            len -= toRead;
        }
        end = millis() - start;
        Serial.printf("%u bytes read for %u ms\n", flen, end);
        file.close();
    } else {
        Serial.println("Failed to open file for reading");
    }


    file = fs.open(path, FILE_WRITE);
    if(!file){
        Serial.println("Failed to open file for writing");
        return;
    }

    size_t i;
    start = millis();
    for(i=0; i<2048; i++){
        file.write(buf, 512);
    }
    end = millis() - start;
    Serial.printf("%u bytes written for %u ms\n", 2048 * 512, end);
    file.close();
}

void setup(){
    Serial.begin(115200);
    while(!Serial); // Wait for COM port to open
    
    if(!SD.begin()){
        Serial.println("Card Mount Failed");
        return;
    }
    uint8_t cardType = SD.cardType();

    if(cardType == CARD_NONE){
        Serial.println("No SD card attached");
        return;
    }

    Serial.print("SD Card Type: ");
    if(cardType == CARD_MMC){
        Serial.println("MMC");
    } else if(cardType == CARD_SD){
        Serial.println("SDSC");
    } else if(cardType == CARD_SDHC){
        Serial.println("SDHC");
    } else {
        Serial.println("UNKNOWN");
    }

    uint64_t cardSize = SD.cardSize() / (1024 * 1024);
    Serial.printf("SD Card Size: %lluMB\n", cardSize);

    // listDir(SD, "/", 0);
    // createDir(SD, "/mydir");
    // listDir(SD, "/", 0);
    // removeDir(SD, "/mydir");
    // listDir(SD, "/", 2);
    writeFile(SD, "/hello.txt", "Hello");
    // appendFile(SD, "/hello.txt", "World!\n");
    // readFile(SD, "/hello.txt");
    // deleteFile(SD, "/foo.txt");
    // renameFile(SD, "/hello.txt", "/foo.txt");
    // readFile(SD, "/foo.txt");
    // testFileIO(SD, "/test.txt");
    Serial.printf("Total space: %lluMB\n", SD.totalBytes() / (1024 * 1024));
    Serial.printf("Used space: %lluMB\n", SD.usedBytes() / (1024 * 1024));
}

void loop(){
    appendFile(SD, "/hello.txt", "World!\n");
    Serial.printf("Used space: %lluMB\n\n", SD.usedBytes() / (1024 * 1024));
    delay(500);
}
```

### Debug Message

```plain
[Starting] Verifying sketch 'examples\ESP32_SD_Card_Test\ESP32_SD_Card_Test.ino'
Please see the build logs in output path: [PROJECT PATH]\Firmware\.arduinobuild
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
exec: "[ARDUINO PATH]\\Arduino\\hardware\\espressif\\esp32/tools/xtensa-esp32s2-elf/bin/xtensa-esp32s2-elf-g++": file does not exist
IntelliSense auto-configuration disabled.
[Error] Verifying sketch 'examples\ESP32_SD_Card_Test\ESP32_SD_Card_Test.ino': Exit with code=1
```

### Other Steps to Reproduce

Followed [manual installation procedure](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html#windows-manual-installation)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by 0x0fe** [comment] 2022-03-28 18:35
well, it seems to be a non issue really, when using get.exe it does install the riscv toolchain but it also install the xtensa toolchain, which is certainly the expected behaviour. get.exe is not target specific, it install both toolchains.

**Comment by Legohead259** [comment] 2022-03-28 18:38
The Xtensa toolchain was not installed on my machine during installation,
hence the issue.

**Comment by 0x0fe** [comment] 2022-03-28 18:38
![image](https://user-images.githubusercontent.com/89607149/160464560-06e48898-749c-4a5f-940b-2cae680496d7.png)
strange..

**Comment by Legohead259** [comment] 2022-03-28 18:45
Agreed.
![image](https://user-images.githubusercontent.com/8077426/160465632-e1e9475b-b60b-411a-857e-886d9b92d1e8.png)

**Comment by me-no-dev** [comment] 2022-03-29 09:34
not extracting for some reason?

**Comment by Legohead259** [comment] 2022-03-30 01:35
That screenshot is right before the terminal window closed. As far as I can tell, the executable is not even attempting to download the right files.

**Comment by lbernstone** [comment] 2022-03-30 01:41
Can you open a terminal window and run get.exe from there?  That way you can see if there is an error happening on the xtensa download.

**Comment by VojtechBartoska** [comment] 2022-04-20 11:14
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable. 

If it's still needed, please reopen the issue.

Thanks for understanding.

**Closed by VojtechBartoska** 2022-04-20 11:14 UTC
Labels: Resolution: Awaiting response
