### ISSUE TITLE
No serial output via USB on ESP32 FireBeetle. Not hardware issue.

### ISSUE THREAD

**Issue by barsznica** [espressif/arduino-esp32#829] opened 2017-11-12 02:22 UTC
### Hardware:
Board:							        DFRobot ESP-WROOM-32
Core Installation/update date:			BN: Unknown board, VID: 2341, PID: 00F3
Chip:                                                                SP32D0WDQ6 (revision 0)
IDE name:							Arduino IDE 1.8.4, Win10 Home, IDF component: N/A
Flash Frequency:					        80, 40Mhz
Upload Speed:						9600, 115200, 921600

### Description:

No serial-over-USB displayed on 'Serial Monitor' when using the Espressif 'Boards' :(

What could I be doing wrong? 

I tried the DFRobot [Board](https://git.oschina.net/dfrobot/FireBeetle-ESP32/raw/master/package_esp32_index.json), from [https://www.dfrobot.com/wiki/index.php/FireBeetle_ESP32...](https://www.dfrobot.com/wiki/index.php/FireBeetle_ESP32_IOT_Microcontroller_(Supports_Wi-Fi_%26_Bluetooth)_SKU:_DFR0478#More), and it works!

The Espressif Board setting compiles code all the code I have tried. Wasn't even using #include <Arduino.h> most of the time :) THANKS HEAPS:)
The DFRobot Board has difficulties compiling the very few, although different, bits of code I have tried ;(

### Sketch:
```cpp

#include <Arduino.h>

void setup() 
{
  delay(1000);
  Serial.begin(115200);
}
 
void loop() 
{
  Serial.println("Hello from FireBeetle ESP32 board");
  delay(2000);
}
```

### Debug Messages:
No errors or warnings, with Max Power at the debug level controls (I be givin' it all I got cap'n).

### DFRobot Board Serial Monitor output, after flash:
ets Jun  8 2016 00:22:57
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0x00
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0008,len:8
load:0x3fff0010,len:1760
load:0x40078000,len:6668
load:0x40080000,len:252
entry 0x40080034
Hello from FireBeetle ESP32 board
Hello from FireBeetle ESP32 board
Hello from FireBeetle ESP32 board
...

### DFRobot Board Serial Monitor output, after reset:
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0x00
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0008,len:8
load:0x3fff0010,len:1760
load:0x40078000,len:6668
load:0x40080000,len:252
entry 0x40080034
Hello from FireBeetle ESP32 board
Hello from FireBeetle ESP32 board
Hello from FireBeetle ESP32 board
...

### Espressif Board Serial Monitor output, after reset:
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download

**Comment by barsznica** [comment] 2017-11-12 03:25
Must be this 'boot:0x3' business.
Hmm, what can I do?

**Comment by barsznica** [comment] 2017-11-12 05:18
I have serial out via TX pin. Woohoo!

**Comment by copercini** [comment] 2017-11-21 11:22
Is your pin 0 connected to something?

**Comment by DzikuVx** [comment] 2017-11-24 11:44
I confirm the same issue with 23cf233ecad1121d56a3a93adbb9de2e5889e665 , no nothing on pin 0

After rolling back to 706bf48708e6668077187ba3f5543d0f7b49e132 , everything works fine again.
Hardware: DOit ESP32 dev kit V1

Looks like bug was introduced somewhere between those 2 commits

**Comment by me-no-dev** [comment] 2017-11-24 12:20
pin 0? what is the issue now? no serial output?

**Comment by DzikuVx** [comment] 2017-11-24 12:22
> The same issue
> No serial-over-USB displayed on 'Serial Monitor' when using the Espressif 'Boards' :(

**Comment by me-no-dev** [comment] 2017-11-24 12:24
nothing at all or does it stop before the sketch starts? any bootloader output?

**Comment by DzikuVx** [comment] 2017-11-24 12:26
@me-no-dev bootloader output present,
 no content available over serial from sketch like this, for example
```
#include <Arduino.h>

void setup() 
{
  delay(1000);
  Serial.begin(115200);
}
 
void loop() 
{
  Serial.println("Hello from FireBeetle ESP32 board");
  delay(2000);
}
```

**Comment by me-no-dev** [comment] 2017-11-24 12:32
I had this happen to me once last night, but then it started working an no fail... will investigate further if I can reproduce it again. Asked around IDF team if they have a clue also.

**Comment by DzikuVx** [comment] 2017-11-24 12:39
Like I wrote, rolling back to 706bf48708e6668077187ba3f5543d0f7b49e132 made that work again

**Comment by me-no-dev** [comment] 2017-11-24 12:40
quite an old commit though ;) it's something between last night and a couple of weeks ago

**Comment by DzikuVx** [comment] 2017-11-24 12:42
I needed EEPROM so just checked out to the oldest commit I was able to use

**Comment by me-no-dev** [comment] 2017-11-24 13:34
can you please pull the last change and give it a go?

**Comment by DzikuVx** [comment] 2017-11-24 20:28
@me-no-dev Looks like it helped. Serial working again in 

For the record, bootloader output
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13076
entry 0x40078ad0
```

I'm not sure it solved problem of @barsznica but mine was solved. Thanks

**Comment by barsznica** [comment] 2017-11-24 21:52
I'll try it out when I get a chance

**Comment by everslick** [comment] 2018-04-19 07:57
New activity in this issue since months, looks as solved. -> closing

**Closed by everslick** 2018-04-19 07:57 UTC

**Comment by iZhangHui** [comment] 2018-07-20 08:25
@me-no-dev 
This issue happen again with FireBeetle board running 1.0.0-rc3. 

After push RST button, Serial Monitor only display the message below:

rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download

When replug the usb, nothing output on Serial Monitor.

**Comment by iZhangHui** [comment] 2018-07-20 14:51
@me-no-dev Thanks for your explanation. 
I didn't connect anything to GPIO0. 

I can upload firmware to the board, when uploading finished, it should be re-plug usb power line.
Then, the board works well with led blink sketch.

But after re-plug usb power line,  Serial Monitor display nothing. In my code I add some codes like Serial.println("******") for debug, and the baud rate is same with Serial Monitor.

**Comment by kalvis84** [comment] 2018-08-15 19:16
I have this problem on DF Fire Beetle. After programming, GPIO0 is held low. It looks like a problem with the software on STM chip that is used as UART-USB converter on that boards.

**Comment by HendrikVE** [comment] 2018-08-18 22:29
I have also problems getting serial output on my FireBeetle (V2.0). Nothing is connected to the board but I measured 3.3 V on GPIO 0. At least I've got the same output as @iZhangHui when I used Arduino IDE to flash, but nothing when using make monitor.

**Comment by kalvis84** [comment] 2018-08-19 08:07
Currently I am using separate uart-usb converter and I have to force reset on stm chip to make it pull up gpio0 again.

**Comment by HendrikVE** [comment] 2018-08-19 15:35
Luckily I've found a UART USB converter at home and I can confirm I'm getting serial output with it. Anyway, it would be cool if I wouldn't need additional hardware. For me its working fine without forcing reset btw.

**Comment by iZhangHui** [comment] 2018-08-20 01:29
@HendrikVE How did you wire the UART USB convetor? Thank you.

**Comment by HendrikVE** [comment] 2018-08-20 11:01
I've put TXD to RXD (GPIO 3) and RXD to TXD (GPIO 1). That's all. My converter appears as ttyUSB0 while the board itself is ttyACM0. You can setup ttyACM0 in `make menuconfig` as default serial port and monitor with `ESPPORT=/dev/ttyUSB0 make monitor`. This way you dont need to rebuild every time in cause of different flash/monitor ports. It's also comfortable to have a USB port with single switches for every USB port as the board will be only flashed if the converter is disconnected from USB.

**Comment by barsznica** [comment] 2018-08-20 13:11
RX, TX & "GND", of course!

**Comment by murali-dotworld** [comment] 2021-05-10 07:00
Arduino Serial monitor not showing the output. Use Putty software, it shows the output
