### ISSUE TITLE
esp32-arduino I2C does not support slave mode?

### ISSUE THREAD

**Issue by linux-downey** [espressif/arduino-esp32#1697] opened 2018-07-30 09:26 UTC
### Hardware:
Board: 							ESP32 Dev Module
Core Installation/update date:			30/jul/2018
IDE name:							Arduino IDE
Flash Frequency:					40Mhz
Upload Speed:						115200

### Description:
Does the esp32-arduino not support I2C-slave-mode now?
I didn't find  any usable example to run in directory esp32\1.0.0-rc3\libraries\Wire\
and,It's seen that there is no API to set slave-mode in a arduino way.

**Comment by stickbreaker** [comment] 2018-07-31 00:32
@linux-downey not yet, still working on something similar to Arduino AVR. 

Chuck.

**Comment by copercini** [comment] 2018-09-21 23:03
Closed as duplicate of https://github.com/espressif/arduino-esp32/issues/118
let's keep the things concentrated =)

**Closed by copercini** 2018-09-21 23:03 UTC

**Comment by tarribas2009** [comment] 2020-03-16 12:41
Any advance or forecast in the I2C slave interface?

**Comment by laercionit** [comment] 2020-05-19 21:01
Someone had succeeded in putting as SLAVE?

**Comment by dpharris** [comment] 2020-09-17 18:27
This is needed.  Can anyone update us on progress of the lack thereof?
Thanks.
