### ISSUE TITLE
Support WiPy 2.0 ?

### ISSUE THREAD

**Issue by sandmen** [espressif/arduino-esp32#972] opened 2018-01-07 08:57 UTC
Is it possible to flash the WiPy from pycom ?
Which board should I select ? Esp32-dev-modul ?

### Hardware:
Board:							WyPi pycom
IDE name:							Arduino IDE 1.8.5

**Comment by beegee-tokyo** [comment] 2018-01-08 06:33
No guarantee, but it should be possible. 
I checked WiPy pinout and Esp32-dev-modul would fit, however some pins are not available on the WiPy board. Flash size is the same as well.

**Comment by sandmen** [comment] 2018-01-08 16:01
Thanks for double checking.
I will try it.
To be honest, thought to put the wipy board into bootloader mode (pin23 to GND), and then using the
Arduino 1.8.5 and arduino-esp32 to "flash" bootloader.
Then, I can use Arduino-IDE for "programming" ... First project with esp32... :-(

Thanks

**Comment by everslick** [comment] 2018-04-19 11:17
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 11:17 UTC
