### ISSUE TITLE
Request getBoardDetails failed with message: 14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by songdf666** [espressif/arduino-esp32#7419] opened 2022-11-01 06:37 UTC
### Board

esp32 dev module

### Device Description

![](https://tuccc.obs.cn-north-4.myhuaweicloud.com/img/20221101143633.png)

### Hardware Configuration

no

### Version

latest development Release Candidate (RC-X)

### IDE Name

Arduino 2.0.1

### Operating System

macOS12.4

### Flash frequency

...

### PSRAM enabled

no

### Upload speed

...

### Description

Request getBoardDetails failed with message: 14 UNAVAILABLE: No connection established

### Sketch

```cpp
..
```

### Debug Message

```plain
..
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Jason2866** [comment] 2022-11-01 10:22
Please use latest actual Arduino Core v2.0.5

**Comment by me-no-dev** [comment] 2022-11-01 18:03
Issue report is not very well filed, but I think the issue is that the board menu item "Get Board Info" does not work?

**Comment by 9trebovirhome** [comment] 2022-11-02 12:47
It is probably not relevant in this repo, but I have the same issue with ESP8266.

**Comment by panciunio** [comment] 2022-11-02 16:21
Issue approaching under Linux MInt 21 and ESP 2.0.5 library installed. Native esp idf.py working fine...

![esp32-2 0 5](https://user-images.githubusercontent.com/9402700/199544244-219a2195-2b0f-456e-8b76-56de1571a0ce.png)

**Comment by rucko24** [comment] 2022-11-05 20:12
> Please use latest actual Arduino Core v2.0.5

Where is this version available ?

**Comment by SuGlider** [comment] 2022-11-05 21:09
> > Please use latest actual Arduino Core v2.0.5
> 
> Where is this version available ?

It is in the releases: https://github.com/espressif/arduino-esp32/releases/tag/2.0.5
It can be obtained by updating the ESP32 core version using IDE->menu->tools->board manager

**Comment by SuGlider** [comment] 2022-11-05 21:15
@songdf666 - My suggestion is to update the IDE to version 2.0.1, recently launched. It may solve this issue.

**Comment by emrullahjack** [comment] 2022-11-12 13:19
I'm having the same issue with an esp32 based board namely "deneyap kart". My OS is linux based and pyserial is already installed. Arduino Core v2.0.5 is also installed.

**Comment by yoann-dufresne** [comment] 2022-11-14 22:24
I have exactly the same error in popOS

**Comment by DonFruendo** [comment] 2022-11-15 18:53
Same here, PopOS 22.04, Arduino 2.0.2-nightly20221115, trying to run sketches on my Arduino Nano

**Comment by KolleparaBharadwaj** [comment] 2022-11-16 13:15
restart the IDE and the computer, it solved the issue for me.

**Comment by yoann-dufresne** [comment] 2022-11-17 09:13
Still not solved for me

**Comment by DonFruendo** [comment] 2022-11-17 09:28
> Still not solved for me

Did you try to revert to an older version and restart your system?

**Comment by emrullahjack** [comment] 2022-11-17 11:54
[This issue](https://github.com/arduino/arduino-cli/issues/1970) might help some of the folks but didn't solve the problem for me.

**Comment by VojtechBartoska** [comment] 2022-12-15 13:29
closing as solved.

**Closed by VojtechBartoska** 2022-12-15 13:29 UTC
Labels: Type: Question, Resolution: Awaiting response, IDE: Arduino IDE
