### ISSUE TITLE
WiFiClientSecure: Memory leak when an SSL Handshake fails

### ISSUE THREAD

**Issue by Phsacar** [espressif/arduino-esp32#5781] opened 2021-10-19 01:32 UTC
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			x
IDE name:						Platform.io
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Ubuntu

### Description:

Hi,
I found a leak in ssl_client.cpp:
If the Handshake fails in start_ssl_client(), and an error is returned, the following section is never reached:
```
  if (rootCABuff != NULL) {
        mbedtls_x509_crt_free(&ssl_client->ca_cert);
    }

    if (cli_cert != NULL) {
        mbedtls_x509_crt_free(&ssl_client->client_cert);
    }

    if (cli_key != NULL) {
        mbedtls_pk_free(&ssl_client->client_key);
    }   
```

There does not seem to be a deconstructor in WiFiClientSecure that handles freeing the memory either.

Background: I am using a CA to connect to an encrypted mqtt server; only after freeing ssl_client->ca_cert myself I stopped having memory leaks.

**Comment by TD-er** [comment] 2021-11-04 08:03
Are you absolutely sure the leak stopped, after manually freeing ca_cert?

I'm looking into this too and I even copied WiFiClientSecure + ssl_client into new classes (with a prefix in the name) to be able to do simple tests by freeing everything that's being accessed via _init functions.
But on average I keep loosing ~1880 bytes per iteration.

Simple test here is to use a CA root certificate (I used the let's encrypt one, but it should not matter) to verify against a self-signed certificate.
I do get `TLS error code: -9984 X509 - Certificate verification failed, e.g. CRL, CA or signature check failed` , which is to be expected. But on each new attempt I loose about 1880 bytes of free heap memory.

I use it for accessing MQTT.
I don't call `loadCACert` as that's obviously leaking memory (see: https://github.com/espressif/arduino-esp32/issues/5826 ) but just call `setCACert`.
Also tested by deleting the WiFiClientSecure object (and implementing the calls to free in the destructor, just to be sure) but does not fix it.

**Comment by TD-er** [comment] 2021-11-04 08:20
OK, scrap that... Apparently I already fixed it myself, but have changed multiple things at once and did not notice it.

I had switched to no longer deleting the WiFiClientSecure, but still did create it and at the same time I had added to free the certificate data.
So now I also have the memory usage stable too.

I can confirm that `ssl_client.h` should have a destructor which needs to call the free functions of everything in the struct.

```c++
sslclient_context::~sslclient_context()
{
    free_ca_cert();
    free_client_cert();
    free_client_key();
}
```
The rest is already freed in the call to `stop()` in `WiFiClientSecure`, but maybe those should also be part of this destructor too as there might be other paths possible, which I don't see right now.

**Comment by ppescher** [comment] 2021-11-17 16:14
I found the same memory leak happens when verification fails, but possibly for many other reasons after review of the source code.
I'm currently testing a fix, I will be back with my findings later.

**Comment by sguarin** [comment] 2021-11-27 19:24
The problem I was having it's related to call malloc again on WiFiClientSecure without freeing the previosly stored certificate.
Related issue with temporary fix here:
#5826

**Comment by TD-er** [comment] 2021-11-27 20:28
The issue you're trying to fix is just when you stream the certificate.
The issue I referred to is related to the client context not being initialized and cleared well when verification fails and you try again to connect.

**Comment by ppescher** [comment] 2021-11-29 14:46
Disregard the first PR, I messed up my forked repo.

In my tests the proposed fix gets rid of memory leaks when the secure connection attempt fails. I simulated troubles in the connection by randomly disconnecting the server side: if this happened during handshake I got memory leaks up to a point where the firmware just fails because of memory allocation errors. With this fix it does not happen anymore.

**Comment by VojtechBartoska** [comment] 2022-04-20 11:20
Can this be closed as mentioned PR was merged already?

**Comment by ppescher** [comment] 2022-04-20 11:49
@VojtechBartoska I'm not the op, but as far as I'm concerned this is fixed and you can close the issue.

**Comment by VojtechBartoska** [comment] 2022-04-22 09:12
Closing as solved.

**Closed by VojtechBartoska** 2022-04-22 09:12 UTC
Labels: Area: BT&Wifi, Resolution: Awaiting response
