### ISSUE TITLE
SD MMC has a memory leak

### ISSUE THREAD

**Issue by skateone** [espressif/arduino-esp32#521] opened 2017-07-17 12:36 UTC
hi there...
i am using the SD_MMC lib in 1 bit mode on my solution and works well... i did notice a memory leak every time i transact with the card.
Looks like i loose about 1.1kb or ram every time i do a file write or read.
any ideas?

**Comment by copercini** [comment] 2017-10-20 15:55
Could you post some code?

**Comment by everslick** [comment] 2018-04-19 06:52
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 06:52 UTC
