### ISSUE TITLE
ESP32 disconnecting from system port after downloading wifi example

### ISSUE THREAD

**Issue by Arun2102** [espressif/arduino-esp32#919] opened 2017-12-12 07:04 UTC
### Hardware: ESP32
Board:	EPS32 WROOM-32			ESP32 Dev Module
Core Installation/update date:		
IDE name:							Arduino IDE
Flash Frequency:					80Mhz
Upload Speed:						115200

### Description:
My esp32 is woking fine for blink example program but when i download SimpleWiFiServer example, the esp32 is getting disconnected from my system port. in this situation i couldnt connect serial port. Also the esp32 is ot connected to the specfied ssid network.
There is no errors during compilation. i have ony entered the ssis and password of my network in the example. nothing else is altered.
The problem occurs for all the wifi example codes. the board is working fine with other examples.

**Comment by lonerzzz** [comment] 2017-12-14 05:31
@Arun2102 Are you holding down the proper 2 pins to set it into bootloader mode and reset? Have you been able to program successfully?

**Comment by Arun2102** [comment] 2017-12-14 16:41
Thank you for your reply Jason. I can able to program successfully. But
after programming the simpleWiFiserver code I couldn't program any other
code.
To program some other example I just pressed and hold down the reset and
when the ide shows connecting il release the reset so that my code will be
programmed successfully. This condition occurs only when I have downloaded
the WiFi examples.
And Janson what is that 2pins to set into bootloader? I couldn't get about
it.

On 14-Dec-2017 11:01 AM, "Jason K." <notifications@github.com> wrote:

@Arun2102 <https://github.com/arun2102> Are you holding down the proper 2
pins to set it into bootloader mode and reset? Have you been able to
program successfully?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/espressif/arduino-esp32/issues/919#issuecomment-351613200>,
or mute the thread

**Comment by PRO2XY** [comment] 2017-12-20 18:13
Sounds like a power supply issue. Are you powering the module using the 3.3V from the USB-Serial converter? If yes, that's your issue. You must use a power source capable of delivering at least 500mA at 3.3V to the module. Also, don't forget, wire length and solder joint quality also affect the actual power delivered.

**Comment by Arun2102** [comment] 2017-12-22 06:09
Thanks for your suggestion.
If i power the module with a separate supply then how i can use serial monitor? 
Also this problem occurs only for the wifi codings. rest all example codes works fine with the USB supply itself.

**Comment by PRO2XY** [comment] 2018-03-20 06:07
I don't know if you got around this issue (it's been > 3 months :-p ), but the reason the problem occurs with WiFi sketches is because WiFi is power intensive. 
As for powering with a separate supply, you connect the ground of the power supply and your serial monitor together. So, if you're using a NodeMCU type board, you can use the USB port for communication, and attach external power supply on the 5V (or 3.3V, if your power supply is 3.3V) pins.

**Comment by kowsche** [comment] 2018-03-27 19:28
I had the exact same problem with COM port getting disconnected when trying out the WiFi samples. The problem was fixed when I used a better quality USB cable to connect from my Laptop to the ESP32 board!!

**Comment by everslick** [comment] 2018-04-19 08:55
This issue is closed, because it looks as if it is not a bug or problem with the ESP32 Arduino core or its support libraries. For general API usage questions or help on specific coding challenges, please visit the [arduino-esp32 Gitter channel](https://gitter.im/espressif/arduino-esp32). If you feel this issue was closed in error, reopen it and comment, why you think this is a bug in the Arduino-Core.

**Closed by everslick** 2018-04-19 08:55 UTC
