### ISSUE TITLE
pinMode on GPIO 13 causes watchdog sw reset loop on ESP32-WROVER-IB

### ISSUE THREAD

**Issue by Frtrillo** [espressif/arduino-esp32#8177] opened 2023-05-10 07:14 UTC
### Board

ESP32-WROVER-IB

### Device Description

ESP32-WROVER-IB DEVKIT

### Hardware Configuration

Nothing attached.

### Version

v2.0.9

### IDE Name

Adruino IDE

### Operating System

mac OS latest

### Flash frequency

240

### PSRAM enabled

no

### Upload speed

921600

### Description

When you do a pinMode on gpio 13 on this chip it makes it a sw reset loop instantly. (log added as debug).
I thought it was a faulty hardware, **but this issue doesn't happen if you try it on ESP-IDF.** (Tried a simple gpio output pin 13 and toggled i.e like for a relay).
Also this doesn't happen on a ESP32-WROVER-B devkit.

### Sketch

```cpp
void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  digitalWrite(13, HIGH);
}
```

### Debug Message

```plain
rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13924
ho 0 tail 12 room 4
load:0x40080400,len:3600
entry 0x400805f0
ets Jun  8 2016 00:22:57
```

### Other Steps to Reproduce

On ESP-IDF there isn't this issue (latest v4.4.4 idf version)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by mrengineer7777** [comment] 2023-05-10 13:27
According to the [WROVER Kit Getting Started page](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-wrover-kit.html), GPIO13 is connected to JTAG.  Are you sure you can use that pin?

**Comment by lbernstone** [comment] 2023-05-10 19:58
Does it do this if you move the write into setup?  The way you have this written, you are hammering the hardware and may not be leaving any cycles for feeding the watchdog.

**Comment by Frtrillo** [comment] 2023-05-11 06:07
> ```c++
> void setup() {
>   pinMode(13, OUTPUT);
> }
> ```

Adding delay doesnt make a difference, and even then, just pinMode makes it reset sw constantly.

void setup() {
  pinMode(13, OUTPUT);
}
and empty loop.

Also regarding your first answer, its no exactly that board, its similiar to a DevKit C.
Also as I said the same example but ported to ESP-IDF SDK works perfectly, but just to make sure its not software only I tried it again measuring voltage with HIGH and LOW on the pin and works without issue but doing 1.61v (instead of 0v) and 3.3v when activated. Other pins do 0v when LOW tho. But at least on ESP-IDF its not an infinite sw_reset.

**Comment by Frtrillo** [comment] 2023-05-15 05:16
> @Frtrillo Can you test the ESP-IDF version using `GPIO_MODE_INPUT_OUTPUT` as that is what Arduino-esp32 uses internally for `OUTPUT`. The usage of `OUTPUT` or `GPIO_MODE_OUTPUT` will prevent reading the current state of the IO pin after a `digitalWrite()` or `gpio_set_level()` call (or it will always return 0 or 1, forget which).

I tried it and does the same as OUTPUT only, it doesnt resets on esp-idf

**Comment by SuGlider** [comment] 2023-05-15 23:32
@Frtrillo 

> I tried it and does the same as OUTPUT only, it doesnt resets on esp-idf

Make sure that the IDF testing "sketch" uses exactly the same `sdkconfig` used in Arduino 2.0.9 for the ESP32.
There may be something that makes it not work correctly with Arduino.

I have seen things like that when PSRAM is enabled and the sketch uses a PSRAM GPIO used as regular IO, but it doesn't seem to be the case with GPIO13.

I have tested it (GPIO13) with a ESP32-WROVER-B board (the ESP-WROVER-KIT board) and I got no issue with the `pinMode(13, OUTPUT)` call.

This issue only happens with the GPIO13?

**Comment by SuGlider** [comment] 2023-05-16 00:20
Other Arduino Core (2.0.1 to 2.0.8) also have the same problem with this board?

**Comment by Frtrillo** [comment] 2023-05-16 09:24
> @Frtrillo
> 
> > I tried it and does the same as OUTPUT only, it doesnt resets on esp-idf
> 
> Make sure that the IDF testing "sketch" uses exactly the same `sdkconfig` used in Arduino 2.0.9 for the ESP32. There may be something that makes it not work correctly with Arduino.
> 
> I have seen things like that when PSRAM is enabled and the sketch uses a PSRAM GPIO used as regular IO, but it doesn't seem to be the case with GPIO13.
> 
> I have tested it (GPIO13) with a ESP32-WROVER-B board (the ESP-WROVER-KIT board) and I got no issue with the `pinMode(13, OUTPUT)` call. (like you said in `Also this doesn't happen on a ESP32-WROVER-B devkit.`).
> 
> This issue only happens with the GPIO13?

I dont know if it uses the same sdkconfig, im using esp-idf 4.3.5 and arduino core 2.0.9





> Other Arduino Core (2.0.1 to 2.0.8) also have the same problem with this board?

Dont know, but I can downgrade and check

**Comment by SuGlider** [comment] 2023-05-16 15:48
>I dont know if it uses the same sdkconfig, im using esp-idf 4.3.5 and arduino core 2.0.9

Ok, but Arduino Core 2.0.x versions are tested and developed using IDF 4.4
Maybe the issue is with the IDF version used in the project that must be compatible with Arduino Core 2.0.9 precompiled libraries...

**Comment by Frtrillo** [comment] 2023-05-18 07:11
> > I dont know if it uses the same sdkconfig, im using esp-idf 4.3.5 and arduino core 2.0.9
> 
> Ok, but Arduino Core 2.0.x versions are tested and developed using IDF 4.4 Maybe the issue is with the IDF version used in the project that must be compatible with Arduino Core 2.0.9 precompiled libraries...
> 
> Anyway... you are not using Arduino as IDF component in your project, right? Arduino IDE with core 2.0.9 uses (pre-compiled) IDF 4.4, therefore using the IDE, everything should work fine.

No, im not using arduino as idf component.
Just tried one code in arduino ide and the other I added here on esp-idf.
Tried arduino core 2.0.1, 2.0.5, and 2.0.9 have same instant reset loop

**Comment by SuGlider** [comment] 2023-05-18 13:41
>Just tried one code in arduino ide and the other I added here on esp-idf.
>Tried arduino core 2.0.1, 2.0.5, and 2.0.9 have same instant reset loop

My final testing suggestion would be to try using the same Arduino `sdkconfig` file with the IDF project, just to check if the issue is in some IDF setup. Please use IDF 4.4.4 instead of 4.3.5.

**Comment by VojtechBartoska** [comment] 2023-08-18 12:35
any updates @Frtrillo?

**Comment by VojtechBartoska** [comment] 2023-08-21 09:27
Ok, closing as expired. Thank you.

**Closed by VojtechBartoska** 2023-08-21 09:27 UTC
Labels: Resolution: Awaiting response
